langs = {
    # CHINESE
    'zh': {
        ('*', 'Quick Metal Materials'): '快速金属材料',
        ('*', 'Noble Metals'): '贵族金属',
        ('Operator', 'Gold'): '黄金',
        ('Operator', 'Gold Fresnel'): '菲涅尔金',
        ('Operator', 'Palladium'): '钯金',
        ('Operator', 'Platinum'): '铂金',
        ('Operator', 'Silver'): '银',
        ('Operator', 'Silver Fresnel'): '菲涅尔银',
        ('*', 'Base Metals'): '基础金属',
        ('Operator', 'Aluminium'): '铝',
        ('Operator', 'Copper'): '铜',
        ('Operator', 'Copper Fresnel'): '菲涅尔铜',
        ('Operator', 'Iron'): '铁',
        ('Operator', 'Lead'): '铅',
        ('Operator', 'Lead Rough'): '粗糙铅',
        ('Operator', 'Nickel'): '镍',
        ('Operator', 'Tin'): '锡',
        ('Operator', 'Titanium Polished'): '抛光钛',
        ('Operator', 'Titanium Textured'): '纹理钛',
        ('Operator', 'Zinc'): '锌',
        ('*', 'Alloys'): '合金',
        ('Operator', 'Brass'): '黄铜',
        ('Operator', 'Bronze'): '青铜',
        ('Operator', 'Chromium'): '铬',
        ('Operator', 'Steel'): '钢',
        ('*', 'Extras'): '额外的',
        ('Operator', 'Asphalt'): '沥青',
        ('Operator', 'Asphalt Bleached'): '白沥青',
        ('Operator', 'Glass Hack'): '玻璃投影',
        ('Operator', 'Mercury'): '水银',
        ('Operator', 'Red Metal'): '红金属',
        ('Operator', 'Rubber Cutting Mat'): '橡胶切割垫',
        ('Operator', 'Tinted Plaster'): '着色的石膏',
        ('Operator', 'Wall Paint'): '墙面漆',
    },
    # UKRAINIAN
    'uk': {
        ('*', 'Quick Metal Materials'): 'Швидкоплавкі металеві матеріали',
        ('*', 'Noble Metals'): 'Благородні метали',
        ('Operator', 'Gold'): 'Золото',
        ('Operator', 'Gold Fresnel'): 'Золото Френеля',
        ('Operator', 'Palladium'): 'Паладій',
        ('Operator', 'Platinum'): 'Платина',
        ('Operator', 'Silver'): 'Срібло',
        ('Operator', 'Silver Fresnel'): 'Срібло Френеля',
        ('*', 'Base Metals'): 'Неблагородні метали',
        ('Operator', 'Aluminium'): 'Алюміній',
        ('Operator', 'Copper'): 'Мідь',
        ('Operator', 'Copper Fresnel'): 'Мідь Френеля',
        ('Operator', 'Iron'): 'Залізо',
        ('Operator', 'Lead'): 'Свинець',
        ('Operator', 'Lead Rough'): 'Свинець чорновий',
        ('Operator', 'Nickel'): 'Нікель',
        ('Operator', 'Tin'): 'Олово',
        ('Operator', 'Titanium Polished'): 'Титан полірований',
        ('Operator', 'Titanium Textured'): 'Титан текстурований',
        ('Operator', 'Zinc'): 'Цинк',
        ('*', 'Alloys'): 'Сплави',
        ('Operator', 'Brass'): 'Латунь',
        ('Operator', 'Bronze'): 'Бронза',
        ('Operator', 'Chromium'): 'Хром',
        ('Operator', 'Steel'): 'Сталь',
        ('*', 'Extras'): 'Додатково',
        ('Operator', 'Asphalt'): 'Асфальт',
        ('Operator', 'Asphalt Bleached'): 'Асфальт вибілений',
        ('Operator', 'Glass Hack'): 'Скляний хак',
        ('Operator', 'Mercury'): 'Ртуть',
        ('Operator', 'Red Metal'): 'Червоний метал',
        ('Operator', 'Rubber Cutting Mat'): 'Гумовий килимок для різання',
        ('Operator', 'Tinted Plaster'): 'Тонована штукатурка',
        ('Operator', 'Wall Paint'): 'Фарба для стін',
    },
    # SWEDISH
    'sv': {
        ('*', 'Quick Metal Materials'): 'Snabba metallmaterial',
        ('*', 'Noble Metals'): 'Ädla metaller',
        ('Operator', 'Gold'): 'Guld',
        ('Operator', 'Gold Fresnel'): 'Guld Fresnel',
        ('Operator', 'Palladium'): 'Palladium',
        ('Operator', 'Platinum'): 'Platina',
        ('Operator', 'Silver'): 'Silver',
        ('Operator', 'Silver Fresnel'): 'Silver Fresnel',
        ('*', 'Base Metals'): 'Basmetaller',
        ('Operator', 'Aluminium'): 'Aluminium',
        ('Operator', 'Copper'): 'Koppar',
        ('Operator', 'Copper Fresnel'): 'Koppar Fresnel',
        ('Operator', 'Iron'): 'Järn',
        ('Operator', 'Lead'): 'Bly',
        ('Operator', 'Lead Rough'): 'Bly Rough',
        ('Operator', 'Nickel'): 'Nickel',
        ('Operator', 'Tin'): 'Tenn',
        ('Operator', 'Titanium Polished'): 'Titan Polerat',
        ('Operator', 'Titanium Textured'): 'Titanium texturerat',
        ('Operator', 'Zinc'): 'Zink',
        ('*', 'Alloys'): 'Legeringar',
        ('Operator', 'Brass'): 'Mässing',
        ('Operator', 'Bronze'): 'Brons',
        ('Operator', 'Chromium'): 'Krom',
        ('Operator', 'Steel'): 'Stål',
        ('*', 'Extras'): 'Extras',
        ('Operator', 'Asphalt'): 'Asfalt',
        ('Operator', 'Asphalt Bleached'): 'Asfalt blekt',
        ('Operator', 'Glass Hack'): 'Glas Hack',
        ('Operator', 'Mercury'): 'Kvicksilver',
        ('Operator', 'Red Metal'): 'Röd metall',
        ('Operator', 'Rubber Cutting Mat'): 'Skärmatta i gummi',
        ('Operator', 'Tinted Plaster'): 'Färgad gips',
        ('Operator', 'Wall Paint'): 'Väggfärg',
    },
    # SLOVAK
    'sk': {
        ('*', 'Quick Metal Materials'): 'Rýchle kovové materiály',
        ('*', 'Noble Metals'): 'Ušľachtilé kovy',
        ('Operator', 'Gold'): 'Zlato',
        ('Operator', 'Gold Fresnel'): 'Zlatý Fresnel',
        ('Operator', 'Palladium'): 'Paládium',
        ('Operator', 'Platinum'): 'Platina',
        ('Operator', 'Silver'): 'Striebro',
        ('Operator', 'Silver Fresnel'): 'Strieborný Fresnel',
        ('*', 'Base Metals'): 'Základné kovy',
        ('Operator', 'Aluminium'): 'Hliník',
        ('Operator', 'Copper'): 'Meď',
        ('Operator', 'Copper Fresnel'): 'Fresnelova meď',
        ('Operator', 'Iron'): 'Železo',
        ('Operator', 'Lead'): 'Olovo',
        ('Operator', 'Lead Rough'): 'Olovo hrubé',
        ('Operator', 'Nickel'): 'Nikel',
        ('Operator', 'Tin'): 'Cín',
        ('Operator', 'Titanium Polished'): 'Titán Leštený',
        ('Operator', 'Titanium Textured'): 'Titán Textúrovaný',
        ('Operator', 'Zinc'): 'Zinok',
        ('*', 'Alloys'): 'Zliatiny',
        ('Operator', 'Brass'): 'Mosadz',
        ('Operator', 'Bronze'): 'Bronz',
        ('Operator', 'Chromium'): 'Chróm',
        ('Operator', 'Steel'): 'Oceľ',
        ('*', 'Extras'): 'Doplnky',
        ('Operator', 'Asphalt'): 'Asfalt',
        ('Operator', 'Asphalt Bleached'): 'Asfalt bielený',
        ('Operator', 'Glass Hack'): 'Sklo Hack',
        ('Operator', 'Mercury'): 'Rtuť',
        ('Operator', 'Red Metal'): 'Červený kov',
        ('Operator', 'Rubber Cutting Mat'): 'Gumová rezná rohož',
        ('Operator', 'Tinted Plaster'): 'Tónovaná omietka',
        ('Operator', 'Wall Paint'): 'Farba na stenu',
    },
    # RUSSIAN
    'ru': {
        ('*', 'Quick Metal Materials'): 'Быстрые металлические материалы',
        ('*', 'Noble Metals'): 'Благородные металлы',
        ('Operator', 'Gold'): 'Золото',
        ('Operator', 'Gold Fresnel'): 'Золото Френеля',
        ('Operator', 'Palladium'): 'Палладий',
        ('Operator', 'Platinum'): 'Платина',
        ('Operator', 'Silver'): 'Серебро',
        ('Operator', 'Silver Fresnel'): 'Серебро Френеля',
        ('*', 'Base Metals'): 'Цветные металлы',
        ('Operator', 'Aluminium'): 'Алюминий',
        ('Operator', 'Copper'): 'Медь',
        ('Operator', 'Copper Fresnel'): 'Медь Френеля',
        ('Operator', 'Iron'): 'Железо',
        ('Operator', 'Lead'): 'Свинец',
        ('Operator', 'Lead Rough'): 'Свинец грубый',
        ('Operator', 'Nickel'): 'Никель',
        ('Operator', 'Tin'): 'Олово',
        ('Operator', 'Titanium Polished'): 'Титан Полированный',
        ('Operator', 'Titanium Textured'): 'Титан текстурированный',
        ('Operator', 'Zinc'): 'Цинк',
        ('*', 'Alloys'): 'Сплавы',
        ('Operator', 'Brass'): 'Латунь',
        ('Operator', 'Bronze'): 'Бронза',
        ('Operator', 'Chromium'): 'Хром',
        ('Operator', 'Steel'): 'Сталь',
        ('*', 'Extras'): 'Дополнительно',
        ('Operator', 'Asphalt'): 'Асфальт',
        ('Operator', 'Asphalt Bleached'): 'Асфальт отбеленный',
        ('Operator', 'Glass Hack'): 'Стекло',
        ('Operator', 'Mercury'): 'Ртуть',
        ('Operator', 'Red Metal'): 'Красный металл',
        ('Operator', 'Rubber Cutting Mat'): 'Резиновый коврик для резки',
        ('Operator', 'Tinted Plaster'): 'Тонированная штукатурка',
        ('Operator', 'Wall Paint'): 'Настенная краска',




    },
    # BRAZILIAN PORTUGUESE
    'pt_BR': {
        ('*', 'Quick Metal Materials'): 'Materiais metálicos rápidos',
        ('*', 'Noble Metals'): 'Metais Nobres',
        ('Operator', 'Gold'): 'Ouro',
        ('Operator', 'Gold Fresnel'): 'Fresnel de Ouro',
        ('Operator', 'Palladium'): 'Palladium',
        ('Operator', 'Platinum'): 'Platina',
        ('Operator', 'Silver'): 'Prata',
        ('Operator', 'Silver Fresnel'): 'Fresnel de prata',
        ('*', 'Base Metals'): 'Metais de Base',
        ('Operator', 'Aluminium'): 'Alumínio',
        ('Operator', 'Copper'): 'Cobre',
        ('Operator', 'Copper Fresnel'): 'Fresnel de cobre',
        ('Operator', 'Iron'): 'Ferro',
        ('Operator', 'Lead'): 'Chumbo',
        ('Operator', 'Lead Rough'): 'Chumbo Rough',
        ('Operator', 'Nickel'): 'Níquel',
        ('Operator', 'Tin'): 'Lata',
        ('Operator', 'Titanium Polished'): 'Polido de titânio',
        ('Operator', 'Titanium Textured'): 'Titânio texturizado',
        ('Operator', 'Zinc'): 'Zinco',
        ('*', 'Alloys'): 'Ligas',
        ('Operator', 'Brass'): 'Latão',
        ('Operator', 'Bronze'): 'Bronze',
        ('Operator', 'Chromium'): 'Cromado',
        ('Operator', 'Steel'): 'Aço',
        ('*', 'Extras'): 'Extras',
        ('Operator', 'Asphalt'): 'Asfalto',
        ('Operator', 'Asphalt Bleached'): 'Asfalto Branqueado',
        ('Operator', 'Glass Hack'): 'Hack de vidro',
        ('Operator', 'Mercury'): 'Mercúrio',
        ('Operator', 'Red Metal'): 'Metal Vermelho',
        ('Operator', 'Rubber Cutting Mat'): 'Tapete de Corte de Borracha',
        ('Operator', 'Tinted Plaster'): 'Estuque colorido',
        ('Operator', 'Wall Paint'): 'Tinta para parede',




    },
    # PORTUGUESE
    'pt': {
        ('*', 'Quick Metal Materials'): 'Materiais metálicos rápidos',
        ('*', 'Noble Metals'): 'Metais Nobres',
        ('Operator', 'Gold'): 'Ouro',
        ('Operator', 'Gold Fresnel'): 'Fresnel de Ouro',
        ('Operator', 'Palladium'): 'Palladium',
        ('Operator', 'Platinum'): 'Platina',
        ('Operator', 'Silver'): 'Prata',
        ('Operator', 'Silver Fresnel'): 'Fresnel de prata',
        ('*', 'Base Metals'): 'Metais de Base',
        ('Operator', 'Aluminium'): 'Alumínio',
        ('Operator', 'Copper'): 'Cobre',
        ('Operator', 'Copper Fresnel'): 'Fresnel de Cobre',
        ('Operator', 'Iron'): 'Ferro de engomar',
        ('Operator', 'Lead'): 'Chumbo',
        ('Operator', 'Lead Rough'): 'Chumbo Rough',
        ('Operator', 'Nickel'): 'Níquel',
        ('Operator', 'Tin'): 'Lata',
        ('Operator', 'Titanium Polished'): 'Polido de titânio',
        ('Operator', 'Titanium Textured'): 'Titânio Texturizado',
        ('Operator', 'Zinc'): 'Zinco',
        ('*', 'Alloys'): 'Ligas',
        ('Operator', 'Brass'): 'Latão',
        ('Operator', 'Bronze'): 'Bronze',
        ('Operator', 'Chromium'): 'Crómio',
        ('Operator', 'Steel'): 'Aço',
        ('*', 'Extras'): 'Extras',
        ('Operator', 'Asphalt'): 'Asfalto',
        ('Operator', 'Asphalt Bleached'): 'Asfalto Branqueado',
        ('Operator', 'Glass Hack'): 'Hack de vidro',
        ('Operator', 'Mercury'): 'Mercúrio',
        ('Operator', 'Red Metal'): 'Metal Vermelho',
        ('Operator', 'Rubber Cutting Mat'): 'Tapete de Corte de Borracha',
        ('Operator', 'Tinted Plaster'): 'Estuque pintado',
        ('Operator', 'Wall Paint'): 'Tinta para Parede',
    },
    # POLISH
    'pl': {
        ('*', 'Quick Metal Materials'): 'Szybkie materiały metalowe',
        ('*', 'Noble Metals'): 'Metale szlachetne',
        ('Operator', 'Gold'): 'Złoto',
        ('Operator', 'Gold Fresnel'): 'Złoto Fresnel',
        ('Operator', 'Palladium'): 'Pallad',
        ('Operator', 'Platinum'): 'Platyna',
        ('Operator', 'Silver'): 'Srebro',
        ('Operator', 'Silver Fresnel'): 'Srebro Fresnel',
        ('*', 'Base Metals'): 'Metale nieszlachetne',
        ('Operator', 'Aluminium'): 'Aluminium',
        ('Operator', 'Copper'): 'Miedź',
        ('Operator', 'Copper Fresnel'): 'Miedź Fresnel',
        ('Operator', 'Iron'): 'Żelazo',
        ('Operator', 'Lead'): 'Ołów',
        ('Operator', 'Lead Rough'): 'Ołów Szorstki',
        ('Operator', 'Nickel'): 'Nikiel',
        ('Operator', 'Tin'): 'Cyna',
        ('Operator', 'Titanium Polished'): 'Tytan Polerowany',
        ('Operator', 'Titanium Textured'): 'Tytan teksturowany',
        ('Operator', 'Zinc'): 'Cynk',
        ('*', 'Alloys'): 'Stopy',
        ('Operator', 'Brass'): 'Mosiądz',
        ('Operator', 'Bronze'): 'Brąz',
        ('Operator', 'Chromium'): 'Chrom',
        ('Operator', 'Steel'): 'Stal',
        ('*', 'Extras'): 'Dodatki',
        ('Operator', 'Asphalt'): 'Asfalt',
        ('Operator', 'Asphalt Bleached'): 'Asfalt Bielony',
        ('Operator', 'Glass Hack'): 'Szkło Hack',
        ('Operator', 'Mercury'): 'Merkury',
        ('Operator', 'Red Metal'): 'Czerwony metal',
        ('Operator', 'Rubber Cutting Mat'): 'Gumowa mata do cięcia',
        ('Operator', 'Tinted Plaster'): 'Tynk barwiony',
        ('Operator', 'Wall Paint'): 'Farba ścienna',
    },
    # DUTCH
    'nl': {
        ('*', 'Quick Metal Materials'): 'Snelle Metaalmaterialen',
        ('*', 'Noble Metals'): 'Edele metalen',
        ('Operator', 'Gold'): 'Goud',
        ('Operator', 'Gold Fresnel'): 'Goud Fresnel',
        ('Operator', 'Palladium'): 'Palladium',
        ('Operator', 'Platinum'): 'Platina',
        ('Operator', 'Silver'): 'Zilver',
        ('Operator', 'Silver Fresnel'): 'Zilver Fresnel',
        ('*', 'Base Metals'): 'Onedele metalen',
        ('Operator', 'Aluminium'): 'Aluminium',
        ('Operator', 'Copper'): 'Koper',
        ('Operator', 'Copper Fresnel'): 'Koper Fresnel',
        ('Operator', 'Iron'): 'IJzer',
        ('Operator', 'Lead'): 'Lood',
        ('Operator', 'Lead Rough'): 'Lood Ruw',
        ('Operator', 'Nickel'): 'Nikkel',
        ('Operator', 'Tin'): 'Tin',
        ('Operator', 'Titanium Polished'): 'Titanium Gepolijst',
        ('Operator', 'Titanium Textured'): 'Titaan getextureerd',
        ('Operator', 'Zinc'): 'Zink',
        ('*', 'Alloys'): 'Legeringen',
        ('Operator', 'Brass'): 'Messing',
        ('Operator', 'Bronze'): 'Brons',
        ('Operator', 'Chromium'): 'Chroom',
        ('Operator', 'Steel'): 'Staal',
        ('*', 'Extras'): 'Extras',
        ('Operator', 'Asphalt'): 'Asfalt',
        ('Operator', 'Asphalt Bleached'): 'Asfalt gebleekt',
        ('Operator', 'Glass Hack'): 'Glazen kappen',
        ('Operator', 'Mercury'): 'Kwik',
        ('Operator', 'Red Metal'): 'Rood Metaal',
        ('Operator', 'Rubber Cutting Mat'): 'Rubber Snijmat',
        ('Operator', 'Tinted Plaster'): 'Getint Gips',
        ('Operator', 'Wall Paint'): 'Muurverf',
    },
    # JAPANESE
    'ja': {
        ('*', 'Quick Metal Materials'): 'クイックメタルマテリアル',
        ('*', 'Noble Metals'): '貴金属',
        ('Operator', 'Gold'): '金',
        ('Operator', 'Gold Fresnel'): 'ゴールドフレネル',
        ('Operator', 'Palladium'): 'パラジウム',
        ('Operator', 'Platinum'): 'プラチナ',
        ('Operator', 'Silver'): '銀',
        ('Operator', 'Silver Fresnel'): '銀フレネル',
        ('*', 'Base Metals'): 'ベースメタル',
        ('Operator', 'Aluminium'): 'アルミニウム',
        ('Operator', 'Copper'): '銅',
        ('Operator', 'Copper Fresnel'): '銅フレネル',
        ('Operator', 'Iron'): '鉄',
        ('Operator', 'Lead'): '鉛',
        ('Operator', 'Lead Rough'): '鉛ラフ',
        ('Operator', 'Nickel'): 'ニッケル',
        ('Operator', 'Tin'): 'スズ',
        ('Operator', 'Titanium Polished'): 'チタン研磨',
        ('Operator', 'Titanium Textured'): 'チタンテクスチャ',
        ('Operator', 'Zinc'): '亜鉛',
        ('*', 'Alloys'): '合金',
        ('Operator', 'Brass'): '真鍮',
        ('Operator', 'Bronze'): 'ブロンズ',
        ('Operator', 'Chromium'): 'クロム',
        ('Operator', 'Steel'): '鋼鉄',
        ('*', 'Extras'): 'その他',
        ('Operator', 'Asphalt'): 'アスファルト',
        ('Operator', 'Asphalt Bleached'): 'アスファルトブリーチ',
        ('Operator', 'Glass Hack'): 'ガラスハック',
        ('Operator', 'Mercury'): 'マーキュリー',
        ('Operator', 'Red Metal'): 'レッドメタル',
        ('Operator', 'Rubber Cutting Mat'): 'ラバーカッティングマット',
        ('Operator', 'Tinted Plaster'): '着色された石膏',
        ('Operator', 'Wall Paint'): 'ウォールペイント',
    },
    # ITALIAN
    'it': {
        ('*', 'Quick Metal Materials'): 'Materiali metallici rapidi',
        ('*', 'Noble Metals'): 'Metalli nobili',
        ('Operator', 'Gold'): 'Oro ',
        ('Operator', 'Gold Fresnel'): 'Oro Fresnel',
        ('Operator', 'Palladium'): 'Palladio',
        ('Operator', 'Platinum'): 'Platino',
        ('Operator', 'Silver'): 'Argento',
        ('Operator', 'Silver Fresnel'): 'Argento Fresnel',
        ('*', 'Base Metals'): 'Metalli comuni',
        ('Operator', 'Aluminium'): 'Alluminio',
        ('Operator', 'Copper'): 'Rame',
        ('Operator', 'Copper Fresnel'): 'Rame Fresnel',
        ('Operator', 'Iron'): 'Ferro',
        ('Operator', 'Lead'): 'Piombo',
        ('Operator', 'Lead Rough'): 'Piombo grezzo',
        ('Operator', 'Nickel'): 'Nichel',
        ('Operator', 'Tin'): 'Stagno',
        ('Operator', 'Titanium Polished'): 'Titanio Lucido',
        ('Operator', 'Titanium Textured'): 'Titanio testurizzato',
        ('Operator', 'Zinc'): 'Zinco',
        ('*', 'Alloys'): 'Leghe',
        ('Operator', 'Brass'): 'Ottone',
        ('Operator', 'Bronze'): 'Bronzo',
        ('Operator', 'Chromium'): 'Cromo',
        ('Operator', 'Steel'): 'Acciaio',
        ('*', 'Extras'): 'Extra',
        ('Operator', 'Asphalt'): 'Asfalto',
        ('Operator', 'Asphalt Bleached'): 'Asfalto sbiancato',
        ('Operator', 'Glass Hack'): 'Vetro Hack',
        ('Operator', 'Mercury'): 'Mercurio',
        ('Operator', 'Red Metal'): 'Metallo rosso',
        ('Operator', 'Rubber Cutting Mat'): 'Tappetino da taglio in gomma',
        ('Operator', 'Tinted Plaster'): 'Intonaco colorato',
        ('Operator', 'Wall Paint'): 'Vernice per pareti',
    },
    # INDONESIAN
    'id': {
        ('*', 'Quick Metal Materials'): 'Bahan Logam Cepat',
        ('*', 'Noble Metals'): 'Logam Mulia',
        ('Operator', 'Gold'): 'Emas',
        ('Operator', 'Gold Fresnel'): 'Fresnel Emas',
        ('Operator', 'Palladium'): 'Paladium',
        ('Operator', 'Platinum'): 'Platinum',
        ('Operator', 'Silver'): 'Perak',
        ('Operator', 'Silver Fresnel'): 'Fresnel Perak',
        ('*', 'Base Metals'): 'Logam Dasar',
        ('Operator', 'Aluminium'): 'Aluminium',
        ('Operator', 'Copper'): 'Tembaga',
        ('Operator', 'Copper Fresnel'): 'Fresnel Tembaga',
        ('Operator', 'Iron'): 'Besi',
        ('Operator', 'Lead'): 'Timbal',
        ('Operator', 'Lead Rough'): 'Timbal Kasar',
        ('Operator', 'Nickel'): 'Nikel',
        ('Operator', 'Tin'): 'Timah',
        ('Operator', 'Titanium Polished'): 'Titanium Dipoles',
        ('Operator', 'Titanium Textured'): 'Titanium Bertekstur',
        ('Operator', 'Zinc'): 'Seng',
        ('*', 'Alloys'): 'Paduan',
        ('Operator', 'Brass'): 'Kuningan',
        ('Operator', 'Bronze'): 'Perunggu',
        ('Operator', 'Chromium'): 'Chromium',
        ('Operator', 'Steel'): 'Baja',
        ('*', 'Extras'): 'Ekstra',
        ('Operator', 'Asphalt'): 'Aspal',
        ('Operator', 'Asphalt Bleached'): 'Aspal Diputihkan',
        ('Operator', 'Glass Hack'): 'Peretasan Kaca',
        ('Operator', 'Mercury'): 'Merkuri',
        ('Operator', 'Red Metal'): 'Logam Merah',
        ('Operator', 'Rubber Cutting Mat'): 'Alas Pemotong Karet',
        ('Operator', 'Tinted Plaster'): 'Plester Berwarna',
        ('Operator', 'Wall Paint'): 'Cat Dinding',
    },
    # HUNGARIAN
    'hu': {
        ('*', 'Quick Metal Materials'): 'Gyors fém anyagok',
        ('*', 'Noble Metals'): 'Nemesfémek',
        ('Operator', 'Gold'): 'Arany',
        ('Operator', 'Gold Fresnel'): 'Arany Fresnel',
        ('Operator', 'Palladium'): 'Palládium',
        ('Operator', 'Platinum'): 'Platina',
        ('Operator', 'Silver'): 'Ezüst',
        ('Operator', 'Silver Fresnel'): 'Ezüst Fresnel',
        ('*', 'Base Metals'): 'Nem nemesfémek',
        ('Operator', 'Aluminium'): 'Alumínium',
        ('Operator', 'Copper'): 'Réz',
        ('Operator', 'Copper Fresnel'): 'Réz Fresnel',
        ('Operator', 'Iron'): 'Vas',
        ('Operator', 'Lead'): 'Ólom',
        ('Operator', 'Lead Rough'): 'Ólom Durva',
        ('Operator', 'Nickel'): 'Nikkel',
        ('Operator', 'Tin'): 'Ón',
        ('Operator', 'Titanium Polished'): 'Titán Csiszolt',
        ('Operator', 'Titanium Textured'): 'Titán Texturált',
        ('Operator', 'Zinc'): 'Cink',
        ('*', 'Alloys'): 'Ötvözetek',
        ('Operator', 'Brass'): 'Sárgaréz',
        ('Operator', 'Bronze'): 'Bronz',
        ('Operator', 'Chromium'): 'Króm',
        ('Operator', 'Steel'): 'Acél',
        ('*', 'Extras'): 'Extrák',
        ('Operator', 'Asphalt'): 'Aszfalt',
        ('Operator', 'Asphalt Bleached'): 'Aszfalt fehérített',
        ('Operator', 'Glass Hack'): 'Üveg Hack',
        ('Operator', 'Mercury'): 'Mercury',
        ('Operator', 'Red Metal'): 'Vörös fém',
        ('Operator', 'Rubber Cutting Mat'): 'Gumi vágószőnyeg',
        ('Operator', 'Tinted Plaster'): 'Színezett vakolat',
        ('Operator', 'Wall Paint'): 'Falfesték',
    },
    # FRENCH
    'fr': {
        ('*', 'Quick Metal Materials'): 'Matériaux en métal rapide',
        ('*', 'Noble Metals'): 'Métaux nobles',
        ('Operator', 'Gold'): 'Or',
        ('Operator', 'Gold Fresnel'): 'Or Fresnel',
        ('Operator', 'Palladium'): 'Palladium',
        ('Operator', 'Platinum'): 'Platine',
        ('Operator', 'Silver'): 'Argent',
        ('Operator', 'Silver Fresnel'): 'Argent Fresnel',
        ('*', 'Base Metals'): 'Métaux de base',
        ('Operator', 'Aluminium'): 'Aluminium',
        ('Operator', 'Copper'): 'Cuivre',
        ('Operator', 'Copper Fresnel'): 'Cuivre Fresnel',
        ('Operator', 'Iron'): 'Fer',
        ('Operator', 'Lead'): 'Plomb',
        ('Operator', 'Lead Rough'): 'Plomb brut',
        ('Operator', 'Nickel'): 'Nickel',
        ('Operator', 'Tin'): 'Étain',
        ('Operator', 'Titanium Polished'): 'Titane poli',
        ('Operator', 'Titanium Textured'): 'Titane texturé',
        ('Operator', 'Zinc'): 'Zinc',
        ('*', 'Alloys'): 'Alliages',
        ('Operator', 'Brass'): 'Laiton',
        ('Operator', 'Bronze'): 'Bronze',
        ('Operator', 'Chromium'): 'Chromium',
        ('Operator', 'Steel'): 'Acier',
        ('*', 'Extras'): 'Extras',
        ('Operator', 'Asphalt'): 'Asphalte',
        ('Operator', 'Asphalt Bleached'): 'Asphalte blanchi',
        ('Operator', 'Glass Hack'): 'Verre Hack',
        ('Operator', 'Mercury'): 'Mercure',
        ('Operator', 'Red Metal'): 'Métal rouge',
        ('Operator', 'Rubber Cutting Mat'): 'Tapis de coupe en caoutchouc',
        ('Operator', 'Tinted Plaster'): 'Plâtre teinté',
        ('Operator', 'Wall Paint'): 'Peinture murale',
    },
    # FINNISH
    'fi': {
        ('*', 'Quick Metal Materials'): 'Nopeat metallimateriaalit',
        ('*', 'Noble Metals'): 'Jalot metallit',
        ('Operator', 'Gold'): 'Kulta',
        ('Operator', 'Gold Fresnel'): 'Kulta Fresnel',
        ('Operator', 'Palladium'): 'Palladium',
        ('Operator', 'Platinum'): 'Platina',
        ('Operator', 'Silver'): 'Hopea',
        ('Operator', 'Silver Fresnel'): 'Hopea Fresnel',
        ('*', 'Base Metals'): 'Perusmetallit',
        ('Operator', 'Aluminium'): 'Alumiini',
        ('Operator', 'Copper'): 'Kupari',
        ('Operator', 'Copper Fresnel'): 'Kupari Fresnel',
        ('Operator', 'Iron'): 'Rauta',
        ('Operator', 'Lead'): 'Lyijy',
        ('Operator', 'Lead Rough'): 'Lyijy Karkea',
        ('Operator', 'Nickel'): 'Nikkeli',
        ('Operator', 'Tin'): 'Tina',
        ('Operator', 'Titanium Polished'): 'Titaani Kiillotettu',
        ('Operator', 'Titanium Textured'): 'Titaani kuvioitu',
        ('Operator', 'Zinc'): 'Sinkki',
        ('*', 'Alloys'): 'Seokset',
        ('Operator', 'Brass'): 'Messinki',
        ('Operator', 'Bronze'): 'Pronssi',
        ('Operator', 'Chromium'): 'Kromi',
        ('Operator', 'Steel'): 'Teräs',
        ('*', 'Extras'): 'Lisävarusteet',
        ('Operator', 'Asphalt'): 'Asfaltti',
        ('Operator', 'Asphalt Bleached'): 'Asfaltti Valkaistu',
        ('Operator', 'Glass Hack'): 'Lasi Hack',
        ('Operator', 'Mercury'): 'Elohopea',
        ('Operator', 'Red Metal'): 'Punainen metalli',
        ('Operator', 'Rubber Cutting Mat'): 'Kumi leikkuumatto',
        ('Operator', 'Tinted Plaster'): 'Sävytetty kipsi',
        ('Operator', 'Wall Paint'): 'Seinämaali',
    },
    # SPANISH
    'es': {
        ('*', 'Quick Metal Materials'): 'Materiales metálicos rápidos',
        ('*', 'Noble Metals'): 'Metales nobles',
        ('Operator', 'Gold'): 'Oro',
        ('Operator', 'Gold Fresnel'): 'Oro Fresnel',
        ('Operator', 'Palladium'): 'Paladio',
        ('Operator', 'Platinum'): 'Platino',
        ('Operator', 'Silver'): 'Plata',
        ('Operator', 'Silver Fresnel'): 'Plata Fresnel',
        ('*', 'Base Metals'): 'Metales base',
        ('Operator', 'Aluminium'): 'Aluminio',
        ('Operator', 'Copper'): 'Cobre',
        ('Operator', 'Copper Fresnel'): 'Cobre Fresnel',
        ('Operator', 'Iron'): 'Hierro',
        ('Operator', 'Lead'): 'Plomo',
        ('Operator', 'Lead Rough'): 'Plomo en bruto',
        ('Operator', 'Nickel'): 'Níquel',
        ('Operator', 'Tin'): 'Estaño',
        ('Operator', 'Titanium Polished'): 'Titanio Pulido',
        ('Operator', 'Titanium Textured'): 'Titanio Texturizado',
        ('Operator', 'Zinc'): 'Zinc',
        ('*', 'Alloys'): 'Aleaciones',
        ('Operator', 'Brass'): 'Latón',
        ('Operator', 'Bronze'): 'Bronce',
        ('Operator', 'Chromium'): 'Cromo',
        ('Operator', 'Steel'): 'Acero',
        ('*', 'Extras'): 'Extras',
        ('Operator', 'Asphalt'): 'Asfalto',
        ('Operator', 'Asphalt Bleached'): 'Asfalto Blanqueado',
        ('Operator', 'Glass Hack'): 'Vidrio Hack',
        ('Operator', 'Mercury'): 'Mercurio',
        ('Operator', 'Red Metal'): 'Metal rojo',
        ('Operator', 'Rubber Cutting Mat'): 'Goma para cortar',
        ('Operator', 'Tinted Plaster'): 'Yeso tintado',
        ('Operator', 'Wall Paint'): 'Pintura de pared',
    },
    # GERMAN
    'de': {
        ('*', 'Quick Metal Materials'): 'Schnelle Metallmaterialien',
        ('*', 'Noble Metals'): 'Edle Metalle',
        ('Operator', 'Gold'): 'Gold',
        ('Operator', 'Gold Fresnel'): 'Gold Fresnel',
        ('Operator', 'Palladium'): 'Palladium',
        ('Operator', 'Platinum'): 'Platin',
        ('Operator', 'Silver'): 'Silber',
        ('Operator', 'Silver Fresnel'): 'Silber Fresnel',
        ('*', 'Base Metals'): 'Unedle Metalle',
        ('Operator', 'Aluminium'): 'Aluminium',
        ('Operator', 'Copper'): 'Kupfer',
        ('Operator', 'Copper Fresnel'): 'Kupfer Fresnel',
        ('Operator', 'Iron'): 'Eisen',
        ('Operator', 'Lead'): 'Blei',
        ('Operator', 'Lead Rough'): 'Blei Grob',
        ('Operator', 'Nickel'): 'Nickel',
        ('Operator', 'Tin'): 'Zinn',
        ('Operator', 'Titanium Polished'): 'Titan Poliert',
        ('Operator', 'Titanium Textured'): 'Titan strukturiert',
        ('Operator', 'Zinc'): 'Zink',
        ('*', 'Alloys'): 'Legierungen',
        ('Operator', 'Brass'): 'Messing',
        ('Operator', 'Bronze'): 'Bronze',
        ('Operator', 'Chromium'): 'Chrom',
        ('Operator', 'Steel'): 'Stahl',
        ('*', 'Extras'): 'Extras',
        ('Operator', 'Asphalt'): 'Asphalt',
        ('Operator', 'Asphalt Bleached'): 'Asphalt gebleicht',
        ('Operator', 'Glass Hack'): 'Glas Hack',
        ('Operator', 'Mercury'): 'Quecksilber',
        ('Operator', 'Red Metal'): 'Rotes Metall',
        ('Operator', 'Rubber Cutting Mat'): 'Gummi-Schneidematte',
        ('Operator', 'Tinted Plaster'): 'Getöntes Pflaster',
        ('Operator', 'Wall Paint'): 'Wandfarbe',
    },
    # DANISH
    'da': {
        ('*', 'Quick Metal Materials'): 'Quick Metal materialer',
        ('*', 'Noble Metals'): 'Ædle metaller',
        ('Operator', 'Gold'): 'Guld',
        ('Operator', 'Gold Fresnel'): 'Guld Fresnel',
        ('Operator', 'Palladium'): 'Palladium',
        ('Operator', 'Platinum'): 'Platin',
        ('Operator', 'Silver'): 'Sølv',
        ('Operator', 'Silver Fresnel'): 'Sølv Fresnel',
        ('*', 'Base Metals'): 'Uædle metaller',
        ('Operator', 'Aluminium'): 'Aluminium',
        ('Operator', 'Copper'): 'Kobber',
        ('Operator', 'Copper Fresnel'): 'Kobber Fresnel',
        ('Operator', 'Iron'): 'Jern',
        ('Operator', 'Lead'): 'Bly',
        ('Operator', 'Lead Rough'): 'Bly Rough',
        ('Operator', 'Nickel'): 'Nikkel',
        ('Operator', 'Tin'): 'Tin',
        ('Operator', 'Titanium Polished'): 'Titanium Poleret',
        ('Operator', 'Titanium Textured'): 'Titanium tekstureret',
        ('Operator', 'Zinc'): 'Zink',
        ('*', 'Alloys'): 'Legeringer',
        ('Operator', 'Brass'): 'Messing',
        ('Operator', 'Bronze'): 'Bronze',
        ('Operator', 'Chromium'): 'Krom',
        ('Operator', 'Steel'): 'Stål',
        ('*', 'Extras'): 'Ekstraudstyr',
        ('Operator', 'Asphalt'): 'Asfalt',
        ('Operator', 'Asphalt Bleached'): 'Asfalt bleget',
        ('Operator', 'Glass Hack'): 'Glas Hack',
        ('Operator', 'Mercury'): 'Kviksølv',
        ('Operator', 'Red Metal'): 'Rødt metal',
        ('Operator', 'Rubber Cutting Mat'): 'Skæremåtte af gummi',
        ('Operator', 'Tinted Plaster'): 'Tonet gips',
        ('Operator', 'Wall Paint'): 'Vægmaling',
    },
}
