langs = {
    # Japanese
    "ja": {
        ("*", "Quick Metal Materials"): "クイックメタル材料",
        ("*", "Set Viewport Color"): "ビューポートの色を設定",
        ("*", "Noble Metals"): "貴金属",
        ("Operator", "Copper"): "銅",
        ("Operator", "Gold"): "金",
        ("Operator", "Palladium"): "パラジウム",
        ("Operator", "Platinum"): "プラチナ",
        ("Operator", "Silver"): "銀",
        ("Operator", "Copper Fresnel"): "銅フレネル",
        ("Operator", "Gold Fresnel"): "金フレネル",
        ("Operator", "Silver Fresnel"): "銀フレネル",
        ("*", "Base Metals"): "卑金属",
        ("Operator", "Aluminium"): "アルミニウム",
        ("Operator", "Iron"): "鉄",
        ("Operator", "Lead"): "鉛",
        ("Operator", "Lead Rough"): "粗鉛",
        ("Operator", "Nickel"): "ニッケル",
        ("Operator", "Tin"): "錫",
        ("Operator", "Zinc"): "亜鉛",
        ("*", "Alloys"): "合金",
        ("Operator", "Brass"): "真鍮",
        ("Operator", "Bronze"): "青銅",
        ("Operator", "Orichalcum"): "オリハルコン",
        ("Operator", "Steel"): "鋼",
        ("*", "    Carbon Steel"): "    炭素鋼",
        ("Operator", "Carbon Steel New"): "炭素鋼（新品）",
        ("Operator", "Carbon Steel Weathered"): "炭素鋼（風化）",
        ("*", "    Stainless Steel"): "    ステンレス鋼",
        ("Operator", "304 Common Stainless Steel"): "304 汎用ステンレス鋼",
        ("Operator", "316 High-Chromium Stainless Steel"): "316 高クロムステンレス鋼",
        ("Operator", "High-Alloy Stainless Steel"): "高合金ステンレス鋼",
        ("*", "    Alloy Steel"): "    合金鋼",
        ("Operator", "4140 Alloy Steel"): "4140 合金鋼",
        ("Operator", "4340 Alloy Steel"): "4340 合金鋼",
        ("Operator", "Nickel-Vanadium Steel"): "ニッケルバナジウム鋼",
        ("Operator", "Manganese Steel"): "マンガン鋼",
        ("Operator", "Tool Steel"): "工具鋼",
        ("Operator", "Spring Steel"): "ばね鋼",
        ("Operator", "Structural Steel"): "構造用鋼",
        ("Operator", "A36 Structural Steel"): "A36 構造用鋼",
        ("Operator", "A572 Structural Steel"): "A572 構造用鋼",
        ("*", "    Specialty Steel"): "    特殊鋼",
        ("Operator", "Case-Hardened Steel A"): "焼入れ鋼 A",
        ("Operator", "Case-Hardened Steel B"): "浸炭焼入れ鋼 B",
        ("Operator", "HSLA Steel"): "HSLA鋼",
        ("Operator", "Maraging Steel"): "マルエージング鋼",
        ("Operator", "Free-Machining Steel"): "快削鋼",
        ("Operator", "Galvanized Steel"): "亜鉛めっき鋼",
        ("Operator", "Weathering Steel"): "耐候性鋼",
        ("Operator", "Virgin Weathering Steel"): "バージン耐候性鋼",
        ("*", "Minor Metals"): "微量金属",
        ("Operator", "Chromium"): "クロム",
        ("Operator", "Mercury"): "水銀",
        ("Operator", "Silicon"): "ケイ素",
        ("Operator", "Titanium Polished"): "チタン研磨",
        ("Operator", "Titanium Textured"): "チタンテクスチャ",
        ("*", "Extras"): "その他",
        ("Operator", "Asphalt"): "アスファルト",
        ("Operator", "Asphalt Bleached"): "漂白アスファルト",
        ("Operator", "Car Paint"): "自動車用塗料",
        ("Operator", "Cinnabar Lacquer"): "辰砂漆",
        ("Operator", "Glass"): "ガラス",
        ("Operator", "Mithryl"): "ミスリル",
        ("Operator", "Rubber Cutting Mat"): "ゴムカッティングマット",
        ("Operator", "Tinted Plaster"): "着色プラスター",
        ("Operator", "Wall Paint"): "壁用塗料",
    },
    # German
    "de": {
        ("*", "Quick Metal Materials"): "Schnell metallische Werkstoffe",
        ("*", "Set Viewport Color"): "Ansichtsfensterfarbe festlegen",
        ("*", "Noble Metals"): "Edelmetalle",
        ("Operator", "Copper"): "Kupfer",
        ("Operator", "Gold"): "Gold",
        ("Operator", "Palladium"): "Palladium",
        ("Operator", "Platinum"): "Platin",
        ("Operator", "Silver"): "Silber",
        ("Operator", "Copper Fresnel"): "Kupfer-Fresnel",
        ("Operator", "Gold Fresnel"): "Gold-Fresnel",
        ("Operator", "Silver Fresnel"): "Silber-Fresnel",
        ("*", "Base Metals"): "Unedle Metalle",
        ("Operator", "Aluminium"): "Aluminium",
        ("Operator", "Iron"): "Eisen",
        ("Operator", "Lead"): "Blei",
        ("Operator", "Lead Rough"): "Blei-Rohmaterial",
        ("Operator", "Nickel"): "Nickel",
        ("Operator", "Tin"): "Zinn",
        ("Operator", "Zinc"): "Zink",
        ("*", "Alloys"): "Legierungen",
        ("Operator", "Brass"): "Messing",
        ("Operator", "Bronze"): "Bronze",
        ("Operator", "Orichalcum"): "Orichalcum",
        ("Operator", "Steel"): "Stahl",
        ("*", "    Carbon Steel"): "    Kohlenstoffstahl",
        ("Operator", "Carbon Steel New"): "Kohlenstoffstahl neu",
        ("Operator", "Carbon Steel Weathered"): "Kohlenstoffstahl verwittert",
        ("*", "    Stainless Steel"): "    Edelstahl",
        ("Operator", "304 Common Stainless Steel"): "304 Gewöhnlicher Edelstahl",
        ("Operator", "316 High-Chromium Stainless Steel"): "316 Hochchromhaltiger Edelstahl",
        ("Operator", "High-Alloy Stainless Steel"): "Hochlegierter Edelstahl",
        ("*", "    Alloy Steel"): "    Legierter Stahl",
        ("Operator", "4140 Alloy Steel"): "4140 Legierter Stahl",
        ("Operator", "4340 Alloy Steel"): "4340 Legierter Stahl",
        ("Operator", "Nickel-Vanadium Steel"): "Nickel-Vanadium-Stahl",
        ("Operator", "Manganese Steel"): "Manganstahl",
        ("Operator", "Tool Steel"): "Werkzeugstahl",
        ("Operator", "Spring Steel"): "Federstahl",
        ("Operator", "Structural Steel"): "Baustahl",
        ("Operator", "A36 Structural Steel"): "A36 Baustahl",
        ("Operator", "A572 Structural Steel"): "A572 Baustahl",
        ("*", "    Specialty Steel"): "    Spezialstahl",
        ("Operator", "Case-Hardened Steel A"): "Einsatzgehärteter Stahl A",
        ("Operator", "Case-Hardened Steel B"): "Einsatzgehärteter Stahl B",
        ("Operator", "HSLA Steel"): "HSLA-Stahl",
        ("Operator", "Maraging Steel"): "Maraging-Stahl",
        ("Operator", "Free-Machining Steel"): "Leicht zu bearbeitender Stahl",
        ("Operator", "Galvanized Steel"): "Verzinkter Stahl",
        ("Operator", "Weathering Steel"): "Wetterfester Stahl",
        ("Operator", "Virgin Weathering Steel"): "Unbehandeltes wetterfestes Stahl",
        ("*", "Minor Metals"): "Nebenmetalle",
        ("Operator", "Chromium"): "Chrom",
        ("Operator", "Mercury"): "Quecksilber",
        ("Operator", "Silicon"): "Silizium",
        ("Operator", "Titanium Polished"): "Poliertes Titan",
        ("Operator", "Titanium Textured"): "Strukturiertes Titan",
        ("*", "Extras"): "Extras",
        ("Operator", "Asphalt"): "Asphalt",
        ("Operator", "Asphalt Bleached"): "Gebleichter Asphalt",
        ("Operator", "Car Paint"): "Autolack",
        ("Operator", "Cinnabar Lacquer"): "Zinnoberlack",
        ("Operator", "Glass"): "Glas",
        ("Operator", "Mithryl"): "Mithryl",
        ("Operator", "Rubber Cutting Mat"): "Gummi-Schneidematte",
        ("Operator", "Tinted Plaster"): "Getönter Putz",
        ("Operator", "Wall Paint"): "Wandfarbe",
    },
    # French
    "fr": {
        ("*", "Quick Metal Materials"): "Matériaux métalliques rapides",
        ("*", "Set Viewport Color"): "Définir la couleur du viewport",
        ("*", "Noble Metals"): "Métaux nobles",
        ("Operator", "Copper"): "Cuivre",
        ("Operator", "Gold"): "Or",
        ("Operator", "Palladium"): "Palladium",
        ("Operator", "Platinum"): "Platine",
        ("Operator", "Silver"): "Argent",
        ("Operator", "Copper Fresnel"): "Fresnel en cuivre",
        ("Operator", "Gold Fresnel"): "Fresnel en or",
        ("Operator", "Silver Fresnel"): "Fresnel en argent",
        ("*", "Base Metals"): "Métaux communs",
        ("Operator", "Aluminium"): "Aluminium",
        ("Operator", "Iron"): "Fer",
        ("Operator", "Lead"): "Plomb",
        ("Operator", "Lead Rough"): "Plomb brut",
        ("Operator", "Nickel"): "Nickel",
        ("Operator", "Tin"): "Étain",
        ("Operator", "Zinc"): "Zinc",
        ("*", "Alloys"): "Alliages",
        ("Operator", "Brass"): "Laiton",
        ("Operator", "Bronze"): "Bronze",
        ("Operator", "Orichalcum"): "Orichalque",
        ("Operator", "Steel"): "Acier",
        ("*", "    Carbon Steel"): "    Acier au carbone",
        ("Operator", "Carbon Steel New"): "Acier au carbone neuf",
        ("Operator", "Carbon Steel Weathered"): "Acier au carbone patiné",
        ("*", "    Stainless Steel"): "    Acier inoxydable",
        ("Operator", "304 Common Stainless Steel"): "Acier inoxydable 304 courant",
        ("Operator", "316 High-Chromium Stainless Steel"): "Acier inoxydable 316 à haute teneur en chrome",
        ("Operator", "High-Alloy Stainless Steel"): "Acier inoxydable fortement allié",
        ("*", "    Alloy Steel"): "    Acier allié",
        ("Operator", "4140 Alloy Steel"): "Acier allié 4140",
        ("Operator", "4340 Alloy Steel"): "Acier allié 4340",
        ("Operator", "Nickel-Vanadium Steel"): "Acier au nickel-vanadium",
        ("Operator", "Manganese Steel"): "Acier au manganèse",
        ("Operator", "Tool Steel"): "Acier à outils",
        ("Operator", "Spring Steel"): "Acier à ressort",
        ("Operator", "Structural Steel"): "Acier de construction",
        ("Operator", "A36 Structural Steel"): "Acier de construction A36",
        ("Operator", "A572 Structural Steel"): "Acier de construction A572",
        ("*", "    Specialty Steel"): "    Acier spécial",
        ("Operator", "Case-Hardened Steel A"): "Acier cémenté A",
        ("Operator", "Case-Hardened Steel B"): "Acier cémenté B",
        ("Operator", "HSLA Steel"): "Acier HSLA",
        ("Operator", "Maraging Steel"): "Acier maraging",
        ("Operator", "Free-Machining Steel"): "Acier à usinabilité améliorée",
        ("Operator", "Galvanized Steel"): "Acier galvanisé",
        ("Operator", "Weathering Steel"): "Acier patiné",
        ("Operator", "Virgin Weathering Steel"): "Acier patiné vierge",
        ("*", "Minor Metals"): "Métaux mineurs",
        ("Operator", "Chromium"): "Chrome",
        ("Operator", "Mercury"): "Mercure",
        ("Operator", "Silicon"): "Silicium",
        ("Operator", "Titanium Polished"): "Titane poli",
        ("Operator", "Titanium Textured"): "Titane texturé",
        ("*", "Extras"): "Extras",
        ("Operator", "Asphalt"): "Asphalte",
        ("Operator", "Asphalt Bleached"): "Asphalte blanchi",
        ("Operator", "Car Paint"): "Peinture automobile",
        ("Operator", "Cinnabar Lacquer"): "Laque cinabre",
        ("Operator", "Glass"): "Verre",
        ("Operator", "Mithryl"): "Mithryl",
        ("Operator", "Rubber Cutting Mat"): "Tapis de découpe en caoutchouc",
        ("Operator", "Tinted Plaster"): "Plâtre teinté",
        ("Operator", "Wall Paint"): "Peinture murale",
    },
    # Russian
    "ru": {
        ("*", "Quick Metal Materials"): "Быстросплавляющиеся металлы",
        ("*", "Set Viewport Color"): "Установить цвет области просмотра",
        ("*", "Noble Metals"): "Благородные металлы",
        ("Operator", "Copper"): "Медь",
        ("Operator", "Gold"): "Золото",
        ("Operator", "Palladium"): "Палладий",
        ("Operator", "Platinum"): "Платина",
        ("Operator", "Silver"): "Серебро",
        ("Operator", "Copper Fresnel"): "Медь Френеля",
        ("Operator", "Gold Fresnel"): "Золото Френеля",
        ("Operator", "Silver Fresnel"): "Серебро Френеля",
        ("*", "Base Metals"): "Неблагородные металлы",
        ("Operator", "Aluminium"): "Алюминий",
        ("Operator", "Iron"): "Железо",
        ("Operator", "Lead"): "Свинец",
        ("Operator", "Lead Rough"): "Свинец необработанный",
        ("Operator", "Nickel"): "Никель",
        ("Operator", "Tin"): "Олово",
        ("Operator", "Zinc"): "Цинк",
        ("*", "Alloys"): "Сплавы",
        ("Operator", "Brass"): "Латунь",
        ("Operator", "Bronze"): "Бронза",
        ("Operator", "Orichalcum"): "Орихалкум",
        ("Operator", "Steel"): "Сталь",
        ("*", "    Carbon Steel"): "    Углеродистая сталь",
        ("Operator", "Carbon Steel New"): "Углеродистая сталь новая",
        ("Operator", "Carbon Steel Weathered"): "Углеродистая сталь выветренная",
        ("*", "    Stainless Steel"): "    Нержавеющая сталь",
        ("Operator", "304 Common Stainless Steel"): "304 Обычная нержавеющая сталь",
        ("Operator", "316 High-Chromium Stainless Steel"): "316 Нержавеющая сталь с высоким содержанием хрома",
        ("Operator", "High-Alloy Stainless Steel"): "Высоколегированная нержавеющая сталь",
        ("*", "    Alloy Steel"): "    Легированная сталь",
        ("Operator", "4140 Alloy Steel"): "4140 Легированная сталь",
        ("Operator", "4340 Alloy Steel"): "4340 Легированная сталь",
        ("Operator", "Nickel-Vanadium Steel"): "Никель-ванадиевая сталь",
        ("Operator", "Manganese Steel"): "Марганцевая сталь",
        ("Operator", "Tool Steel"): "Инструментальная сталь",
        ("Operator", "Spring Steel"): "Пружинная сталь",
        ("Operator", "Structural Steel"): "Конструкционная сталь",
        ("Operator", "A36 Structural Steel"): "A36 Конструкционная сталь",
        ("Operator", "A572 Structural Steel"): "A572 Конструкционная сталь",
        ("*", "    Specialty Steel"): "    Специальная сталь",
        ("Operator", "Case-Hardened Steel A"): "Цементационная сталь A",
        ("Operator", "Case-Hardened Steel B"): "Цементированная сталь B",
        ("Operator", "HSLA Steel"): "Сталь HSLA",
        ("Operator", "Maraging Steel"): "Марганцевая сталь",
        ("Operator", "Free-Machining Steel"): "Легкообрабатываемая сталь",
        ("Operator", "Galvanized Steel"): "Оцинкованная сталь",
        ("Operator", "Weathering Steel"): "Погодостойкая сталь",
        ("Operator", "Virgin Weathering Steel"): "Необработанная погодостойкая сталь",
        ("*", "Minor Metals"): "Вторичные металлы",
        ("Operator", "Chromium"): "Хром",
        ("Operator", "Mercury"): "Ртуть",
        ("Operator", "Silicon"): "Кремний",
        ("Operator", "Titanium Polished"): "Титан полированный",
        ("Operator", "Titanium Textured"): "Титан текстурированный",
        ("*", "Extras"): "Дополнительные материалы",
        ("Operator", "Asphalt"): "Асфальт",
        ("Operator", "Asphalt Bleached"): "Асфальт отбеленный",
        ("Operator", "Car Paint"): "Автомобильная краска",
        ("Operator", "Cinnabar Lacquer"): "Киноварь лак",
        ("Operator", "Glass"): "Стекло",
        ("Operator", "Mithryl"): "Мифрил",
        ("Operator", "Rubber Cutting Mat"): "Резиновый коврик для резки",
        ("Operator", "Tinted Plaster"): "Тонированная штукатурка",
        ("Operator", "Wall Paint"): "Краска для стен",
    },
    # Italian
    "it": {
        ("*", "Quick Metal Materials"): "Materiali metallici rapidi",
        ("*", "Set Viewport Color"): "Imposta il colore della vista",
        ("*", "Noble Metals"): "Metalli nobili",
        ("Operator", "Copper"): "Rame",
        ("Operator", "Gold"): "Oro",
        ("Operator", "Palladium"): "Palladio",
        ("Operator", "Platinum"): "Platino",
        ("Operator", "Silver"): "Argento",
        ("Operator", "Copper Fresnel"): "Fresnel in rame",
        ("Operator", "Gold Fresnel"): "Fresnel in oro",
        ("Operator", "Silver Fresnel"): "Fresnel in argento",
        ("*", "Base Metals"): "Metalli di base",
        ("Operator", "Aluminium"): "Alluminio",
        ("Operator", "Iron"): "Ferro",
        ("Operator", "Lead"): "Piombo",
        ("Operator", "Lead Rough"): "Piombo grezzo",
        ("Operator", "Nickel"): "Nichel",
        ("Operator", "Tin"): "Stagno",
        ("Operator", "Zinc"): "Zinco",
        ("*", "Alloys"): "Leghe",
        ("Operator", "Brass"): "Ottone",
        ("Operator", "Bronze"): "Bronzo",
        ("Operator", "Orichalcum"): "Orichalcum",
        ("Operator", "Steel"): "Acciaio",
        ("*", "    Carbon Steel"): "    Acciaio al carbonio",
        ("Operator", "Carbon Steel New"): "Acciaio al carbonio nuovo",
        ("Operator", "Carbon Steel Weathered"): "Acciaio al carbonio invecchiato",
        ("*", "    Stainless Steel"): "    Acciaio inossidabile",
        ("Operator", "304 Common Stainless Steel"): "Acciaio inossidabile comune 304",
        ("Operator", "316 High-Chromium Stainless Steel"): "Acciaio inossidabile ad alto contenuto di cromo 316",
        ("Operator", "High-Alloy Stainless Steel"): "Acciaio inossidabile altolegato",
        ("*", "    Alloy Steel"): "    Acciaio legato",
        ("Operator", "4140 Alloy Steel"): "Acciaio legato 4140",
        ("Operator", "4340 Alloy Steel"): "Acciaio legato 4340",
        ("Operator", "Nickel-Vanadium Steel"): "Acciaio al nichel-vanadio",
        ("Operator", "Manganese Steel"): "Acciaio al manganese",
        ("Operator", "Tool Steel"): "Acciaio per utensili",
        ("Operator", "Spring Steel"): "Acciaio per molle",
        ("Operator", "Structural Steel"): "Acciaio strutturale",
        ("Operator", "A36 Structural Steel"): "Acciaio strutturale A36",
        ("Operator", "A572 Structural Steel"): "Acciaio strutturale A572",
        ("*", "    Specialty Steel"): "    Acciaio speciale",
        ("Operator", "Case-Hardened Steel A"): "Acciaio cementato A",
        ("Operator", "Case-Hardened Steel B"): "Acciaio cementato B",
        ("Operator", "HSLA Steel"): "Acciaio HSLA",
        ("Operator", "Maraging Steel"): "Acciaio maraging",
        ("Operator", "Free-Machining Steel"): "Acciaio automatico",
        ("Operator", "Galvanized Steel"): "Acciaio zincato",
        ("Operator", "Weathering Steel"): "Acciaio resistente agli agenti atmosferici",
        ("Operator", "Virgin Weathering Steel"): "Acciaio vergine resistente agli agenti atmosferici",
        ("*", "Minor Metals"): "Metalli minori",
        ("Operator", "Chromium"): "Cromo",
        ("Operator", "Mercury"): "Mercurio",
        ("Operator", "Silicon"): "Silicio",
        ("Operator", "Titanium Polished"): "Titanio lucido",
        ("Operator", "Titanium Textured"): "Titanio testurizzato",
        ("*", "Extras"): "Extra",
        ("Operator", "Asphalt"): "Asfalto",
        ("Operator", "Asphalt Bleached"): "Asfalto sbiancato",
        ("Operator", "Car Paint"): "Vernice per auto",
        ("Operator", "Cinnabar Lacquer"): "Lacca cinabro",
        ("Operator", "Glass"): "Vetro",
        ("Operator", "Mithryl"): "Mithryl",
        ("Operator", "Rubber Cutting Mat"): "Tappetino da taglio in gomma",
        ("Operator", "Tinted Plaster"): "Intonaco colorato",
        ("Operator", "Wall Paint"): "Vernice per pareti",
    },
    # Brazilian Portuguese
    "pt_BR": {
        ("*", "Quick Metal Materials"): "Materiais metálicos rápidos",
        ("*", "Set Viewport Color"): "Definir cor da janela de visualização",
        ("*", "Noble Metals"): "Metais nobres",
        ("Operator", "Copper"): "Cobre",
        ("Operator", "Gold"): "Ouro",
        ("Operator", "Palladium"): "Paládio",
        ("Operator", "Platinum"): "Platina",
        ("Operator", "Silver"): "Prata",
        ("Operator", "Copper Fresnel"): "Fresnel de cobre",
        ("Operator", "Gold Fresnel"): "Fresnel de ouro",
        ("Operator", "Silver Fresnel"): "Fresnel de prata",
        ("*", "Base Metals"): "Metais básicos",
        ("Operator", "Aluminium"): "Alumínio",
        ("Operator", "Iron"): "Ferro",
        ("Operator", "Lead"): "Chumbo",
        ("Operator", "Lead Rough"): "Chumbo bruto",
        ("Operator", "Nickel"): "Níquel",
        ("Operator", "Tin"): "Estanho",
        ("Operator", "Zinc"): "Zinco",
        ("*", "Alloys"): "Ligas",
        ("Operator", "Brass"): "Latão",
        ("Operator", "Bronze"): "Bronze",
        ("Operator", "Orichalcum"): "Orichalcum",
        ("Operator", "Steel"): "Aço",
        ("*", "    Carbon Steel"): "    Aço carbono",
        ("Operator", "Carbon Steel New"): "Aço carbono novo",
        ("Operator", "Carbon Steel Weathered"): "Aço carbono envelhecido",
        ("*", "    Stainless Steel"): "    Aço inoxidável",
        ("Operator", "304 Common Stainless Steel"): "Aço inoxidável comum 304",
        ("Operator", "316 High-Chromium Stainless Steel"): "Aço inoxidável com alto teor de cromo 316",
        ("Operator", "High-Alloy Stainless Steel"): "Aço inoxidável de alta liga",
        ("*", "    Alloy Steel"): "    Aço de liga",
        ("Operator", "4140 Alloy Steel"): "Aço de liga 4140",
        ("Operator", "4340 Alloy Steel"): "Aço de liga 4340",
        ("Operator", "Nickel-Vanadium Steel"): "Aço níquel-vanádio",
        ("Operator", "Manganese Steel"): "Aço manganês",
        ("Operator", "Tool Steel"): "Aço para ferramentas",
        ("Operator", "Spring Steel"): "Aço para molas",
        ("Operator", "Structural Steel"): "Aço estrutural",
        ("Operator", "A36 Structural Steel"): "Aço estrutural A36",
        ("Operator", "A572 Structural Steel"): "Aço estrutural A572",
        ("*", "    Specialty Steel"): "    Aço especial",
        ("Operator", "Case-Hardened Steel A"): "Aço cementado A",
        ("Operator", "Case-Hardened Steel B"): "Aço cementado B",
        ("Operator", "HSLA Steel"): "Aço HSLA",
        ("Operator", "Maraging Steel"): "Aço maraging",
        ("Operator", "Free-Machining Steel"): "Aço de usinagem livre",
        ("Operator", "Galvanized Steel"): "Aço galvanizado",
        ("Operator", "Weathering Steel"): "Aço resistente às intempéries",
        ("Operator", "Virgin Weathering Steel"): "Aço virgem resistente às intempéries",
        ("*", "Minor Metals"): "Metais menores",
        ("Operator", "Chromium"): "Cromo",
        ("Operator", "Mercury"): "Mercúrio",
        ("Operator", "Silicon"): "Silício",
        ("Operator", "Titanium Polished"): "Titânio polido",
        ("Operator", "Titanium Textured"): "Titânio texturizado",
        ("*", "Extras"): "Extras",
        ("Operator", "Asphalt"): "Asfalto",
        ("Operator", "Asphalt Bleached"): "Asfalto branqueado",
        ("Operator", "Car Paint"): "Tinta automotiva",
        ("Operator", "Cinnabar Lacquer"): "Laca cinábrio",
        ("Operator", "Glass"): "Vidro",
        ("Operator", "Mithryl"): "Mithryl",
        ("Operator", "Rubber Cutting Mat"): "Tapete de corte de borracha",
        ("Operator", "Tinted Plaster"): "Gesso colorido",
        ("Operator", "Wall Paint"): "Tinta para parede",
    },
    # Spanish
    "es": {
        ("*", "Quick Metal Materials"): "Materiales metálicos rápidos",
        ("*", "Set Viewport Color"): "Establecer el color de la ventana gráfica",
        ("*", "Noble Metals"): "Metales nobles",
        ("Operator", "Copper"): "Cobre",
        ("Operator", "Gold"): "Oro",
        ("Operator", "Palladium"): "Paladio",
        ("Operator", "Platinum"): "Platino",
        ("Operator", "Silver"): "Plata",
        ("Operator", "Copper Fresnel"): "Fresnel de cobre",
        ("Operator", "Gold Fresnel"): "Fresnel de oro",
        ("Operator", "Silver Fresnel"): "Fresnel de plata",
        ("*", "Base Metals"): "Metales básicos",
        ("Operator", "Aluminium"): "Aluminio",
        ("Operator", "Iron"): "Hierro",
        ("Operator", "Lead"): "Plomo",
        ("Operator", "Lead Rough"): "Plomo en bruto",
        ("Operator", "Nickel"): "Níquel",
        ("Operator", "Tin"): "Estaño",
        ("Operator", "Zinc"): "Zinc",
        ("*", "Alloys"): "Aleaciones",
        ("Operator", "Brass"): "Latón",
        ("Operator", "Bronze"): "Bronce",
        ("Operator", "Orichalcum"): "Orichalcum",
        ("Operator", "Steel"): "Acero",
        ("*", "    Carbon Steel"): "    Acero al carbono",
        ("Operator", "Carbon Steel New"): "Acero al carbono nuevo",
        ("Operator", "Carbon Steel Weathered"): "Acero al carbono envejecido",
        ("*", "    Stainless Steel"): "    Acero inoxidable",
        ("Operator", "304 Common Stainless Steel"): "Acero inoxidable común 304",
        ("Operator", "316 High-Chromium Stainless Steel"): "Acero inoxidable con alto contenido en cromo 316",
        ("Operator", "High-Alloy Stainless Steel"): "Acero inoxidable de alta aleación",
        ("*", "    Alloy Steel"): "    Acero aleado",
        ("Operator", "4140 Alloy Steel"): "Acero aleado 4140",
        ("Operator", "4340 Alloy Steel"): "Acero aleado 4340",
        ("Operator", "Nickel-Vanadium Steel"): "Acero al níquel-vanadio",
        ("Operator", "Manganese Steel"): "Acero al manganeso",
        ("Operator", "Tool Steel"): "Acero para herramientas",
        ("Operator", "Spring Steel"): "Acero para resortes",
        ("Operator", "Structural Steel"): "Acero estructural",
        ("Operator", "A36 Structural Steel"): "Acero estructural A36",
        ("Operator", "A572 Structural Steel"): "Acero estructural A572",
        ("*", "    Specialty Steel"): "    Acero especial",
        ("Operator", "Case-Hardened Steel A"): "Acero cementado A",
        ("Operator", "Case-Hardened Steel B"): "Acero cementado B",
        ("Operator", "HSLA Steel"): "Acero HSLA",
        ("Operator", "Maraging Steel"): "Acero martensítico",
        ("Operator", "Free-Machining Steel"): "Acero de fácil mecanización",
        ("Operator", "Galvanized Steel"): "Acero galvanizado",
        ("Operator", "Weathering Steel"): "Acero resistente a la intemperie",
        ("Operator", "Virgin Weathering Steel"): "Acero virgen resistente a la intemperie",
        ("*", "Minor Metals"): "Metales menores",
        ("Operator", "Chromium"): "Cromo",
        ("Operator", "Mercury"): "Mercurio",
        ("Operator", "Silicon"): "Silicio",
        ("Operator", "Titanium Polished"): "Titanio pulido",
        ("Operator", "Titanium Textured"): "Titanio texturizado",
        ("*", "Extras"): "Extras",
        ("Operator", "Asphalt"): "Asfalto",
        ("Operator", "Asphalt Bleached"): "Asfalto blanqueado",
        ("Operator", "Car Paint"): "Pintura para automóviles",
        ("Operator", "Cinnabar Lacquer"): "Laca de cinabrio",
        ("Operator", "Glass"): "Vidrio",
        ("Operator", "Mithryl"): "Mithryl",
        ("Operator", "Rubber Cutting Mat"): "Esterilla de corte de caucho",
        ("Operator", "Tinted Plaster"): "Yeso tintado",
        ("Operator", "Wall Paint"): "Pintura para paredes",
    },
    # Indonesian
    "id_ID": {
        ("*", "Quick Metal Materials"): "Bahan Logam Cepat",
        ("*", "Set Viewport Color"): "Atur warna tampilan",
        ("*", "Noble Metals"): "Logam Mulia",
        ("Operator", "Copper"): "Tembaga",
        ("Operator", "Gold"): "Emas",
        ("Operator", "Palladium"): "Palladium",
        ("Operator", "Platinum"): "Platinum",
        ("Operator", "Silver"): "Perak",
        ("Operator", "Copper Fresnel"): "Tembaga Fresnel",
        ("Operator", "Gold Fresnel"): "Emas Fresnel",
        ("Operator", "Silver Fresnel"): "Perak Fresnel",
        ("*", "Base Metals"): "Logam Dasar",
        ("Operator", "Aluminium"): "Aluminium",
        ("Operator", "Iron"): "Besi",
        ("Operator", "Lead"): "Timah",
        ("Operator", "Lead Rough"): "Timah Kasar",
        ("Operator", "Nickel"): "Nikel",
        ("Operator", "Tin"): "Timah",
        ("Operator", "Zinc"): "Seng",
        ("*", "Alloys"): "Paduan",
        ("Operator", "Brass"): "Kuningan",
        ("Operator", "Bronze"): "Bronze",
        ("Operator", "Orichalcum"): "Orichalcum",
        ("Operator", "Steel"): "Baja",
        ("*", "    Carbon Steel"): "    Baja Karbon",
        ("Operator", "Carbon Steel New"): "Baja Karbon Baru",
        ("Operator", "Carbon Steel Weathered"): "Baja Karbon Teroksidasi",
        ("*", "    Stainless Steel"): "    Baja Tahan Karat",
        ("Operator", "304 Common Stainless Steel"): "Baja Tahan Karat 304 Umum",
        ("Operator", "316 High-Chromium Stainless Steel"): "Baja Tahan Karat 316 Berkromium Tinggi",
        ("Operator", "High-Alloy Stainless Steel"): "Baja Tahan Karat Paduan Tinggi",
        ("*", "    Alloy Steel"): "    Baja Paduan",
        ("Operator", "4140 Alloy Steel"): "Baja Paduan 4140",
        ("Operator", "4340 Alloy Steel"): "Baja Paduan 4340",
        ("Operator", "Nickel-Vanadium Steel"): "Baja Nikel-Vanadium",
        ("Operator", "Manganese Steel"): "Baja Mangan",
        ("Operator", "Tool Steel"): "Baja Alat",
        ("Operator", "Spring Steel"): "Baja Pegas",
        ("Operator", "Structural Steel"): "Baja Struktur",
        ("Operator", "A36 Structural Steel"): "Baja Struktur A36",
        ("Operator", "A572 Structural Steel"): "Baja Struktur A572",
        ("*", "    Specialty Steel"): "    Baja Khusus",
        ("Operator", "Case-Hardened Steel A"): "Baja Pengeras Permukaan A",
        ("Operator", "Case-Hardened Steel B"): "Baja Pengeras Permukaan B",
        ("Operator", "HSLA Steel"): "Baja HSLA",
        ("Operator", "Maraging Steel"): "Baja Maraging",
        ("Operator", "Free-Machining Steel"): "Baja Pemotongan Bebas",
        ("Operator", "Galvanized Steel"): "Baja Galvanis",
        ("Operator", "Weathering Steel"): "Baja Korosi",
        ("Operator", "Virgin Weathering Steel"): "Baja Korosi Murni",
        ("*", "Minor Metals"): "Logam Minor",
        ("Operator", "Chromium"): "Kromium",
        ("Operator", "Mercury"): "Merkuri",
        ("Operator", "Silicon"): "Silikon",
        ("Operator", "Titanium Polished"): "Titanium Polished",
        ("Operator", "Titanium Textured"): "Titanium Bertekstur",
        ("*", "Extras"): "Ekstra",
        ("Operator", "Asphalt"): "Aspal",
        ("Operator", "Asphalt Bleached"): "Aspal Putih",
        ("Operator", "Car Paint"): "Cat Mobil",
        ("Operator", "Cinnabar Lacquer"): "Cat Cinnabar",
        ("Operator", "Glass"): "Kaca",
        ("Operator", "Mithryl"): "Mithryl",
        ("Operator", "Rubber Cutting Mat"): "Mat Pemotong Karet",
        ("Operator", "Tinted Plaster"): "Plester Berwarna",
        ("Operator", "Wall Paint"): "Cat Dinding",
    },
    # Chinese Traditional
    "zh": {
        ("*", "Quick Metal Materials"): "快速金屬材料",
        ("*", "Set Viewport Color"): "設定檢視區顏色",
        ("*", "Noble Metals"): "貴金屬",
        ("Operator", "Copper"): "銅",
        ("Operator", "Gold"): "金",
        ("Operator", "Palladium"): "鈀",
        ("Operator", "Platinum"): "鉑",
        ("Operator", "Silver"): "銀",
        ("Operator", "Copper Fresnel"): "銅菲涅爾",
        ("Operator", "Gold Fresnel"): "金菲涅爾",
        ("Operator", "Silver Fresnel"): "銀菲涅爾",
        ("*", "Base Metals"): "基本金屬",
        ("Operator", "Aluminium"): "鋁",
        ("Operator", "Iron"): "鐵",
        ("Operator", "Lead"): "鉛",
        ("Operator", "Lead Rough"): "粗鉛",
        ("Operator", "Nickel"): "鎳",
        ("Operator", "Tin"): "錫",
        ("Operator", "Zinc"): "鋅",
        ("*", "Alloys"): "合金",
        ("Operator", "Brass"): "黃銅",
        ("Operator", "Bronze"): "青銅",
        ("Operator", "Orichalcum"): "奧利哈鋼",
        ("Operator", "Steel"): "鋼材",
        ("*", "    Carbon Steel"): "    碳鋼",
        ("Operator", "Carbon Steel New"): "新型碳鋼",
        ("Operator", "Carbon Steel Weathered"): "風化碳鋼",
        ("*", "    Stainless Steel"): "    不鏽鋼",
        ("Operator", "304 Common Stainless Steel"): "304通用不鏽鋼",
        ("Operator", "316 High-Chromium Stainless Steel"): "316高鉻不鏽鋼",
        ("Operator", "High-Alloy Stainless Steel"): "高合金不鏽鋼",
        ("*", "    Alloy Steel"): "    合金鋼",
        ("Operator", "4140 Alloy Steel"): "4140合金鋼",
        ("Operator", "4340 Alloy Steel"): "4340合金鋼",
        ("Operator", "Nickel-Vanadium Steel"): "鎳釩鋼",
        ("Operator", "Manganese Steel"): "錳鋼",
        ("Operator", "Tool Steel"): "工具鋼",
        ("Operator", "Spring Steel"): "彈簧鋼",
        ("Operator", "Structural Steel"): "結構鋼",
        ("Operator", "A36 Structural Steel"): "A36結構鋼",
        ("Operator", "A572 Structural Steel"): "A572結構鋼",
        ("*", "    Specialty Steel"): "    特種鋼材",
        ("Operator", "Case-Hardened Steel A"): "表面淬火鋼A",
        ("Operator", "Case-Hardened Steel B"): "表面淬火鋼 B",
        ("Operator", "HSLA Steel"): "高強度低合金鋼",
        ("Operator", "Maraging Steel"): "時效鋼",
        ("Operator", "Free-Machining Steel"): "易切削鋼",
        ("Operator", "Galvanized Steel"): "鍍鋅鋼",
        ("Operator", "Weathering Steel"): "耐候鋼",
        ("Operator", "Virgin Weathering Steel"): "原生耐候鋼",
        ("*", "Minor Metals"): "微量金屬",
        ("Operator", "Chromium"): "鉻",
        ("Operator", "Mercury"): "汞",
        ("Operator", "Silicon"): "矽",
        ("Operator", "Titanium Polished"): "拋光鈦",
        ("Operator", "Titanium Textured"): "紋理鈦",
        ("*", "Extras"): "附加材料",
        ("Operator", "Asphalt"): "瀝青",
        ("Operator", "Asphalt Bleached"): "漂白瀝青",
        ("Operator", "Car Paint"): "汽車漆",
        ("Operator", "Cinnabar Lacquer"): "朱砂漆",
        ("Operator", "Glass"): "玻璃",
        ("Operator", "Mithryl"): "密特瑞爾",
        ("Operator", "Rubber Cutting Mat"): "橡膠切割墊",
        ("Operator", "Tinted Plaster"): "有色灰泥",
        ("Operator", "Wall Paint"): "牆面漆",
    },
    # Korean
    "ko": {
        ("*", "Quick Metal Materials"): "고속 금속 재료",
        ("*", "Set Viewport Color"): "뷰포트 색상 설정",
        ("*", "Noble Metals"): "귀금속",
        ("Operator", "Copper"): "구리",
        ("Operator", "Gold"): "금",
        ("Operator", "Palladium"): "팔라듐",
        ("Operator", "Platinum"): "백금",
        ("Operator", "Silver"): "은",
        ("Operator", "Copper Fresnel"): "구리 프레넬",
        ("Operator", "Gold Fresnel"): "금 프레넬",
        ("Operator", "Silver Fresnel"): "은 프레넬",
        ("*", "Base Metals"): "비귀금속",
        ("Operator", "Aluminium"): "알루미늄",
        ("Operator", "Iron"): "철",
        ("Operator", "Lead"): "납",
        ("Operator", "Lead Rough"): "납 거친",
        ("Operator", "Nickel"): "니켈",
        ("Operator", "Tin"): "주석",
        ("Operator", "Zinc"): "아연",
        ("*", "Alloys"): "합금",
        ("Operator", "Brass"): "황동",
        ("Operator", "Bronze"): "청동",
        ("Operator", "Orichalcum"): "오리칼쿰",
        ("Operator", "Steel"): "강철",
        ("*", "    Carbon Steel"): "    탄소강",
        ("Operator", "Carbon Steel New"): "탄소강 신형",
        ("Operator", "Carbon Steel Weathered"): "탄소강 풍화",
        ("*", "    Stainless Steel"): "    스테인리스강",
        ("Operator", "304 Common Stainless Steel"): "304 일반 스테인리스강",
        ("Operator", "316 High-Chromium Stainless Steel"): "316 고크롬 스테인리스강",
        ("Operator", "High-Alloy Stainless Steel"): "고합금 스테인리스강",
        ("*", "    Alloy Steel"): "    합금강",
        ("Operator", "4140 Alloy Steel"): "4140 합금강",
        ("Operator", "4340 Alloy Steel"): "4340 합금강",
        ("Operator", "Nickel-Vanadium Steel"): "니켈-바나듐강",
        ("Operator", "Manganese Steel"): "망간강",
        ("Operator", "Tool Steel"): "공구강",
        ("Operator", "Spring Steel"): "스프링강",
        ("Operator", "Structural Steel"): "구조용 강재",
        ("Operator", "A36 Structural Steel"): "A36 구조용 강재",
        ("Operator", "A572 Structural Steel"): "A572 구조용 강재",
        ("*", "    Specialty Steel"): "    특수강",
        ("Operator", "Case-Hardened Steel A"): "경화강 A",
        ("Operator", "Case-Hardened Steel B"): "침탄강 B",
        ("Operator", "HSLA Steel"): "HSLA 강",
        ("Operator", "Maraging Steel"): "마라이징강",
        ("Operator", "Free-Machining Steel"): "자유가공강",
        ("Operator", "Galvanized Steel"): "아연도금강",
        ("Operator", "Weathering Steel"): "내후성강",
        ("Operator", "Virgin Weathering Steel"): "버진 내후성강",
        ("*", "Minor Metals"): "미량 금속",
        ("Operator", "Chromium"): "크롬",
        ("Operator", "Mercury"): "수은",
        ("Operator", "Silicon"): "실리콘",
        ("Operator", "Titanium Polished"): "티타늄 광택",
        ("Operator", "Titanium Textured"): "티타늄 텍스처",
        ("*", "Extras"): "추가 재료",
        ("Operator", "Asphalt"): "아스팔트",
        ("Operator", "Asphalt Bleached"): "표백 아스팔트",
        ("Operator", "Car Paint"): "자동차 페인트",
        ("Operator", "Cinnabar Lacquer"): "진사 래커",
        ("Operator", "Glass"): "유리",
        ("Operator", "Mithryl"): "미스릴",
        ("Operator", "Rubber Cutting Mat"): "고무 커팅 매트",
        ("Operator", "Tinted Plaster"): "착색 석고",
        ("Operator", "Wall Paint"): "벽 페인트",
    },
    # Polish
    "pl": {
        ("*", "Quick Metal Materials"): "Szybkie materiały metalowe",
        ("*", "Set Viewport Color"): "Ustaw kolor widoku",
        ("*", "Noble Metals"): "Metale szlachetne",
        ("Operator", "Copper"): "Miedź",
        ("Operator", "Gold"): "Złoto",
        ("Operator", "Palladium"): "Pallad",
        ("Operator", "Platinum"): "Platyna",
        ("Operator", "Silver"): "Srebro",
        ("Operator", "Copper Fresnel"): "Miedź Fresnel",
        ("Operator", "Gold Fresnel"): "Złoto Fresnel",
        ("Operator", "Silver Fresnel"): "Srebro Fresnel",
        ("*", "Base Metals"): "Metale nieszlachetne",
        ("Operator", "Aluminium"): "Aluminium",
        ("Operator", "Iron"): "Żelazo",
        ("Operator", "Lead"): "Ołów",
        ("Operator", "Lead Rough"): "Ołów surowy",
        ("Operator", "Nickel"): "Nikiel",
        ("Operator", "Tin"): "Cynę",
        ("Operator", "Zinc"): "Cynk",
        ("*", "Alloys"): "Stopy",
        ("Operator", "Brass"): "Mosiądz",
        ("Operator", "Bronze"): "Brąz",
        ("Operator", "Orichalcum"): "Orichalcum",
        ("Operator", "Steel"): "Stal",
        ("*", "    Carbon Steel"): "    Stal węglowa",
        ("Operator", "Carbon Steel New"): "Stal węglowa nowa",
        ("Operator", "Carbon Steel Weathered"): "Stal węglowa zwietrzała",
        ("*", "    Stainless Steel"): "    Stal nierdzewna",
        ("Operator", "304 Common Stainless Steel"): "Stal nierdzewna 304",
        ("Operator", "316 High-Chromium Stainless Steel"): "Stal nierdzewna 316 o wysokiej zawartości chromu",
        ("Operator", "High-Alloy Stainless Steel"): "Stal nierdzewna wysokostopowa",
        ("*", "    Alloy Steel"): "    Stal stopowa",
        ("Operator", "4140 Alloy Steel"): "Stal stopowa 4140",
        ("Operator", "4340 Alloy Steel"): "Stal stopowa 4340",
        ("Operator", "Nickel-Vanadium Steel"): "Stal niklowo-wanadowa",
        ("Operator", "Manganese Steel"): "Stal manganowa",
        ("Operator", "Tool Steel"): "Stal narzędziowa",
        ("Operator", "Spring Steel"): "Stal sprężynowa",
        ("Operator", "Structural Steel"): "Stal konstrukcyjna",
        ("Operator", "A36 Structural Steel"): "Stal konstrukcyjna A36",
        ("Operator", "A572 Structural Steel"): "Stal konstrukcyjna A572",
        ("*", "    Specialty Steel"): "    Stal specjalna",
        ("Operator", "Case-Hardened Steel A"): "Stal utwardzana powierzchniowo A",
        ("Operator", "Case-Hardened Steel B"): "Stal utwardzana powierzchniowo B",
        ("Operator", "HSLA Steel"): "Stal HSLA",
        ("Operator", "Maraging Steel"): "Stal maragingowa",
        ("Operator", "Free-Machining Steel"): "Stal łatwoobrabialna",
        ("Operator", "Galvanized Steel"): "Stal ocynkowana",
        ("Operator", "Weathering Steel"): "Stal odporna na warunki atmosferyczne",
        ("Operator", "Virgin Weathering Steel"): "Stal odporna na warunki atmosferyczne Virgin",
        ("*", "Minor Metals"): "Metale drugorzędne",
        ("Operator", "Chromium"): "Chrom",
        ("Operator", "Mercury"): "Rtęć",
        ("Operator", "Silicon"): "Krzem",
        ("Operator", "Titanium Polished"): "Tytan polerowany",
        ("Operator", "Titanium Textured"): "Tytan teksturowany",
        ("*", "Extras"): "Dodatki",
        ("Operator", "Asphalt"): "Asfalt",
        ("Operator", "Asphalt Bleached"): "Asfalt bielony",
        ("Operator", "Car Paint"): "Farba samochodowa",
        ("Operator", "Cinnabar Lacquer"): "Lakier cynobrowy",
        ("Operator", "Glass"): "Szkło",
        ("Operator", "Mithryl"): "Mithryl",
        ("Operator", "Rubber Cutting Mat"): "Gumowa mata do cięcia",
        ("Operator", "Tinted Plaster"): "Barwiony tynk",
        ("Operator", "Wall Paint"): "Farba ścienna",
    },
    # Turkish
    "tr": {
        ("*", "Quick Metal Materials"): "Hızlı Metal Malzemeler",
        ("*", "Set Viewport Color"): "Görünüm alanı rengini ayarla",
        ("*", "Noble Metals"): "Asil Metaller",
        ("Operator", "Copper"): "Bakır",
        ("Operator", "Gold"): "Altın",
        ("Operator", "Palladium"): "Paladyum",
        ("Operator", "Platinum"): "Platin",
        ("Operator", "Silver"): "Gümüş",
        ("Operator", "Copper Fresnel"): "Bakır Fresnel",
        ("Operator", "Gold Fresnel"): "Altın Fresnel",
        ("Operator", "Silver Fresnel"): "Gümüş Fresnel",
        ("*", "Base Metals"): "Baz Metaller",
        ("Operator", "Aluminium"): "Alüminyum",
        ("Operator", "Iron"): "Demir",
        ("Operator", "Lead"): "Kurşun",
        ("Operator", "Lead Rough"): "Kaba Kurşun",
        ("Operator", "Nickel"): "Nikel",
        ("Operator", "Tin"): "Kalay",
        ("Operator", "Zinc"): "Çinko",
        ("*", "Alloys"): "Alaşımlar",
        ("Operator", "Brass"): "Pirinç",
        ("Operator", "Bronze"): "Bronz",
        ("Operator", "Orichalcum"): "Orichalcum",
        ("Operator", "Steel"): "Çelik",
        ("*", "    Carbon Steel"): "    Karbon Çelik",
        ("Operator", "Carbon Steel New"): "Yeni Karbon Çelik",
        ("Operator", "Carbon Steel Weathered"): "Aşınmış Karbon Çelik",
        ("*", "    Stainless Steel"): "    Paslanmaz Çelik",
        ("Operator", "304 Common Stainless Steel"): "304 Yaygın Paslanmaz Çelik",
        ("Operator", "316 High-Chromium Stainless Steel"): "316 Yüksek Kromlu Paslanmaz Çelik",
        ("Operator", "High-Alloy Stainless Steel"): "Yüksek Alaşımlı Paslanmaz Çelik",
        ("*", "    Alloy Steel"): "    Alaşımlı Çelik",
        ("Operator", "4140 Alloy Steel"): "4140 Alaşımlı Çelik",
        ("Operator", "4340 Alloy Steel"): "4340 Alaşımlı Çelik",
        ("Operator", "Nickel-Vanadium Steel"): "Nikel-Vanadyum Çelik",
        ("Operator", "Manganese Steel"): "Manganez Çelik",
        ("Operator", "Tool Steel"): "Takım Çelik",
        ("Operator", "Spring Steel"): "Yay Çelik",
        ("Operator", "Structural Steel"): "Yapısal Çelik",
        ("Operator", "A36 Structural Steel"): "A36 Yapısal Çelik",
        ("Operator", "A572 Structural Steel"): "A572 Yapısal Çelik",
        ("*", "    Specialty Steel"): "    Özel Çelik",
        ("Operator", "Case-Hardened Steel A"): "Sertleştirilmiş Çelik A",
        ("Operator", "Case-Hardened Steel B"): "Sertleştirilmiş Çelik B",
        ("Operator", "HSLA Steel"): "HSLA Çelik",
        ("Operator", "Maraging Steel"): "Maraging Çelik",
        ("Operator", "Free-Machining Steel"): "Kolay İşlenebilir Çelik",
        ("Operator", "Galvanized Steel"): "Galvanizli Çelik",
        ("Operator", "Weathering Steel"): "Hava Koşullarına Dayanıklı Çelik",
        ("Operator", "Virgin Weathering Steel"): "Saf Hava Koşullarına Dayanıklı Çelik",
        ("*", "Minor Metals"): "Minör Metaller",
        ("Operator", "Chromium"): "Krom",
        ("Operator", "Mercury"): "Cıva",
        ("Operator", "Silicon"): "Silikon",
        ("Operator", "Titanium Polished"): "Titan Parlak",
        ("Operator", "Titanium Textured"): "Titan Dokulu",
        ("*", "Extras"): "Ekstra",
        ("Operator", "Asphalt"): "Asfalt",
        ("Operator", "Asphalt Bleached"): "Asfalt Ağartılmış",
        ("Operator", "Car Paint"): "Araba Boyası",
        ("Operator", "Cinnabar Lacquer"): "Cinnabar Lake",
        ("Operator", "Glass"): "Cam",
        ("Operator", "Mithryl"): "Mithryl",
        ("Operator", "Rubber Cutting Mat"): "Kauçuk Kesme Matı",
        ("Operator", "Tinted Plaster"): "Renkli Sıva",
        ("Operator", "Wall Paint"): "Duvar Boyası",
    },
    # Dutch
    "nl": {
        ("*", "Quick Metal Materials"): "Snelle metalen materialen",
        ("*", "Set Viewport Color"): "Weergavekleur instellen",
        ("*", "Noble Metals"): "Edelmetalen",
        ("Operator", "Copper"): "Koper",
        ("Operator", "Gold"): "Goud",
        ("Operator", "Palladium"): "Palladium",
        ("Operator", "Platinum"): "Platina",
        ("Operator", "Silver"): "Zilver",
        ("Operator", "Copper Fresnel"): "Koper Fresnel",
        ("Operator", "Gold Fresnel"): "Goud Fresnel",
        ("Operator", "Silver Fresnel"): "Zilver Fresnel",
        ("*", "Base Metals"): "Onedele metalen",
        ("Operator", "Aluminium"): "Aluminium",
        ("Operator", "Iron"): "IJzer",
        ("Operator", "Lead"): "Lood",
        ("Operator", "Lead Rough"): "Ruw lood",
        ("Operator", "Nickel"): "Nikkel",
        ("Operator", "Tin"): "Tin",
        ("Operator", "Zinc"): "Zink",
        ("*", "Alloys"): "Legeringen",
        ("Operator", "Brass"): "Messing",
        ("Operator", "Bronze"): "Brons",
        ("Operator", "Orichalcum"): "Orichalcum",
        ("Operator", "Steel"): "Staal",
        ("*", "    Carbon Steel"): "    Koolstofstaal",
        ("Operator", "Carbon Steel New"): "Nieuw koolstofstaal",
        ("Operator", "Carbon Steel Weathered"): "Verweerd koolstofstaal",
        ("*", "    Stainless Steel"): "    Roestvrij staal",
        ("Operator", "304 Common Stainless Steel"): "304 Gewoon roestvrij staal",
        ("Operator", "316 High-Chromium Stainless Steel"): "316 Roestvrij staal met hoog chroomgehalte",
        ("Operator", "High-Alloy Stainless Steel"): "Hooggelegeerd roestvrij staal",
        ("*", "    Alloy Steel"): "    Gelegeerd staal",
        ("Operator", "4140 Alloy Steel"): "4140 Gelegeerd staal",
        ("Operator", "4340 Alloy Steel"): "4340 Gelegeerd staal",
        ("Operator", "Nickel-Vanadium Steel"): "Nikkel-vanadiumstaal",
        ("Operator", "Manganese Steel"): "Mangaanstaal",
        ("Operator", "Tool Steel"): "Gereedschapsstaal",
        ("Operator", "Spring Steel"): "Veerstaal",
        ("Operator", "Structural Steel"): "Constructiestaal",
        ("Operator", "A36 Structural Steel"): "A36 Constructiestaal",
        ("Operator", "A572 Structural Steel"): "A572 Constructiestaal",
        ("*", "    Specialty Steel"): "    Speciaal staal",
        ("Operator", "Case-Hardened Steel A"): "Gehard staal A",
        ("Operator", "Case-Hardened Steel B"): "Gehard staal B",
        ("Operator", "HSLA Steel"): "HSLA-staal",
        ("Operator", "Maraging Steel"): "Maraging-staal",
        ("Operator", "Free-Machining Steel"): "Vrij bewerkbaar staal",
        ("Operator", "Galvanized Steel"): "Gegalvaniseerd staal",
        ("Operator", "Weathering Steel"): "Verweringsstaal",
        ("Operator", "Virgin Weathering Steel"): "Virgin verweringsstaal",
        ("*", "Minor Metals"): "Kleine metalen",
        ("Operator", "Chromium"): "Chroom",
        ("Operator", "Mercury"): "Kwik",
        ("Operator", "Silicon"): "Silicium",
        ("Operator", "Titanium Polished"): "Titanium gepolijst",
        ("Operator", "Titanium Textured"): "Titanium gestructureerd",
        ("*", "Extras"): "Extra's",
        ("Operator", "Asphalt"): "Asfalt",
        ("Operator", "Asphalt Bleached"): "Asfalt gebleekt",
        ("Operator", "Car Paint"): "Autolak",
        ("Operator", "Cinnabar Lacquer"): "Cinnaberlak",
        ("Operator", "Glass"): "Glas",
        ("Operator", "Mithryl"): "Mithryl",
        ("Operator", "Rubber Cutting Mat"): "Rubber snijmat",
        ("Operator", "Tinted Plaster"): "Getinte pleister",
        ("Operator", "Wall Paint"): "Muurverf",
    },
    # Ukrainian
    "uk": {
        ("*", "Quick Metal Materials"): "Швидкі металеві матеріали",
        ("*", "Set Viewport Color"): "Встановити колір області перегляду",
        ("*", "Noble Metals"): "Благородні метали",
        ("Operator", "Copper"): "Мідь",
        ("Operator", "Gold"): "Золото",
        ("Operator", "Palladium"): "Паладій",
        ("Operator", "Platinum"): "Платина",
        ("Operator", "Silver"): "Срібло",
        ("Operator", "Copper Fresnel"): "Мідний френель",
        ("Operator", "Gold Fresnel"): "Золотий френель",
        ("Operator", "Silver Fresnel"): "Срібний френель",
        ("*", "Base Metals"): "Неблагородні метали",
        ("Operator", "Aluminium"): "Алюміній",
        ("Operator", "Iron"): "Залізо",
        ("Operator", "Lead"): "Свинець",
        ("Operator", "Lead Rough"): "Неочищений свинець",
        ("Operator", "Nickel"): "Нікель",
        ("Operator", "Tin"): "Олово",
        ("Operator", "Zinc"): "Цинк",
        ("*", "Alloys"): "Сплави",
        ("Operator", "Brass"): "Латунь",
        ("Operator", "Bronze"): "Бронза",
        ("Operator", "Orichalcum"): "Оріхалкум",
        ("Operator", "Steel"): "Сталь",
        ("*", "    Carbon Steel"): "    Вуглецева сталь",
        ("Operator", "Carbon Steel New"): "Вуглецева сталь нова",
        ("Operator", "Carbon Steel Weathered"): "Вуглецева сталь витримана",
        ("*", "    Stainless Steel"): "    Нержавіюча сталь",
        ("Operator", "304 Common Stainless Steel"): "304 Звичайна нержавіюча сталь",
        ("Operator", "316 High-Chromium Stainless Steel"): "316 Нержавіюча сталь з високим вмістом хрому",
        ("Operator", "High-Alloy Stainless Steel"): "Високолегована нержавіюча сталь",
        ("*", "    Alloy Steel"): "    Легована сталь",
        ("Operator", "4140 Alloy Steel"): "4140 Легована сталь",
        ("Operator", "4340 Alloy Steel"): "4340 Легована сталь",
        ("Operator", "Nickel-Vanadium Steel"): "Нікель-ванадієва сталь",
        ("Operator", "Manganese Steel"): "Марганцева сталь",
        ("Operator", "Tool Steel"): "Інструментальна сталь",
        ("Operator", "Spring Steel"): "Пружинна сталь",
        ("Operator", "Structural Steel"): "Конструкційна сталь",
        ("Operator", "A36 Structural Steel"): "A36 Конструкційна сталь",
        ("Operator", "A572 Structural Steel"): "A572 Конструкційна сталь",
        ("*", "    Specialty Steel"): "    Спеціальна сталь",
        ("Operator", "Case-Hardened Steel A"): "Цементована сталь A",
        ("Operator", "Case-Hardened Steel B"): "Цементована сталь B",
        ("Operator", "HSLA Steel"): "Сталь HSLA",
        ("Operator", "Maraging Steel"): "Марганцева сталь",
        ("Operator", "Free-Machining Steel"): "Легкооброблювана сталь",
        ("Operator", "Galvanized Steel"): "Оцинкована сталь",
        ("Operator", "Weathering Steel"): "Погодостійка сталь",
        ("Operator", "Virgin Weathering Steel"): "Необроблена погодостійка сталь",
        ("*", "Minor Metals"): "Незначні метали",
        ("Operator", "Chromium"): "Хром",
        ("Operator", "Mercury"): "Ртуть",
        ("Operator", "Silicon"): "Кремній",
        ("Operator", "Titanium Polished"): "Полірований титан",
        ("Operator", "Titanium Textured"): "Текстурований титан",
        ("*", "Extras"): "Додаткові матеріали",
        ("Operator", "Asphalt"): "Асфальт",
        ("Operator", "Asphalt Bleached"): "Вибілений асфальт",
        ("Operator", "Car Paint"): "Автомобільна фарба",
        ("Operator", "Cinnabar Lacquer"): "Лак з кіновар'ю",
        ("Operator", "Glass"): "Скло",
        ("Operator", "Mithryl"): "Мітріл",
        ("Operator", "Rubber Cutting Mat"): "Гумовий килимок для різання",
        ("Operator", "Tinted Plaster"): "Тонований штукатурка",
        ("Operator", "Wall Paint"): "Фарба для стін",
    },
    # Hungarian
    "hu": {
        ("*", "Quick Metal Materials"): "Gyors fémanyagok",
        ("*", "Set Viewport Color"): "Nézetport színének beállítása",
        ("*", "Noble Metals"): "Nemesfémek",
        ("Operator", "Copper"): "Réz",
        ("Operator", "Gold"): "Arany",
        ("Operator", "Palladium"): "Palládium",
        ("Operator", "Platinum"): "Platina",
        ("Operator", "Silver"): "Ezüst",
        ("Operator", "Copper Fresnel"): "Réz Fresnel",
        ("Operator", "Gold Fresnel"): "Arany Fresnel",
        ("Operator", "Silver Fresnel"): "Ezüst Fresnel",
        ("*", "Base Metals"): "Nem nemesfémek",
        ("Operator", "Aluminium"): "Alumínium",
        ("Operator", "Iron"): "Vas",
        ("Operator", "Lead"): "Ólom",
        ("Operator", "Lead Rough"): "Ólom durva",
        ("Operator", "Nickel"): "Nikkel",
        ("Operator", "Tin"): "Ón",
        ("Operator", "Zinc"): "Cink",
        ("*", "Alloys"): "Ötvözetek",
        ("Operator", "Brass"): "Sárgaréz",
        ("Operator", "Bronze"): "Bronz",
        ("Operator", "Orichalcum"): "Orichalcum",
        ("Operator", "Steel"): "Acél",
        ("*", "    Carbon Steel"): "    Szénacél",
        ("Operator", "Carbon Steel New"): "Szénacél új",
        ("Operator", "Carbon Steel Weathered"): "Szénacél időjárásálló",
        ("*", "    Stainless Steel"): "    Rozsdamentes acél",
        ("Operator", "304 Common Stainless Steel"): "304 Közönséges rozsdamentes acél",
        ("Operator", "316 High-Chromium Stainless Steel"): "316 Magas krómtartalmú rozsdamentes acél",
        ("Operator", "High-Alloy Stainless Steel"): "Magas ötvözésű rozsdamentes acél",
        ("*", "    Alloy Steel"): "    Ötvözött acél",
        ("Operator", "4140 Alloy Steel"): "4140 Ötvözött acél",
        ("Operator", "4340 Alloy Steel"): "4340 Ötvözött acél",
        ("Operator", "Nickel-Vanadium Steel"): "Nikkel-vanádium acél",
        ("Operator", "Manganese Steel"): "Mangán acél",
        ("Operator", "Tool Steel"): "Szerszámacél",
        ("Operator", "Spring Steel"): "Rugóacél",
        ("Operator", "Structural Steel"): "Szerkezeti acél",
        ("Operator", "A36 Structural Steel"): "A36 Szerkezeti acél",
        ("Operator", "A572 Structural Steel"): "A572 Szerkezeti acél",
        ("*", "    Specialty Steel"): "    Speciális acél",
        ("Operator", "Case-Hardened Steel A"): "Edzett acél A",
        ("Operator", "Case-Hardened Steel B"): "Cseppkeményített acél B",
        ("Operator", "HSLA Steel"): "HSLA acél",
        ("Operator", "Maraging Steel"): "Maraging acél",
        ("Operator", "Free-Machining Steel"): "Könnyen megmunkálható acél",
        ("Operator", "Galvanized Steel"): "Horganyzott acél",
        ("Operator", "Weathering Steel"): "Időjárásálló acél",
        ("Operator", "Virgin Weathering Steel"): "Szűz időjárásálló acél",
        ("*", "Minor Metals"): "Kisebb fémek",
        ("Operator", "Chromium"): "Króm",
        ("Operator", "Mercury"): "Higany",
        ("Operator", "Silicon"): "Szilícium",
        ("Operator", "Titanium Polished"): "Titán polírozott",
        ("Operator", "Titanium Textured"): "Titán texturált",
        ("*", "Extras"): "Extrák",
        ("Operator", "Asphalt"): "Aszfalt",
        ("Operator", "Asphalt Bleached"): "Aszfalt fehérített",
        ("Operator", "Car Paint"): "Autófesték",
        ("Operator", "Cinnabar Lacquer"): "Cinnabar lakk",
        ("Operator", "Glass"): "Üveg",
        ("Operator", "Mithryl"): "Mithryl",
        ("Operator", "Rubber Cutting Mat"): "Gumi vágódeszka",
        ("Operator", "Tinted Plaster"): "Színezett vakolat",
        ("Operator", "Wall Paint"): "Falfesték",
    },
}
