langs = {
  'zh': {
    ('*', 'Quick Metal Materials'): '快速金属材料',
    ('*', 'Noble Metals'): '贵族金属',
    ('Operator', 'Gold'): '黄金',
    ('Operator', 'Gold Fresnel'): '菲涅尔金',
    ('Operator', 'Palladium'): '钯金',
    ('Operator', 'Platinum'): '铂金',
    ('Operator', 'Silver'): '银',
    ('Operator', 'Silver Fresnel'): '菲涅尔银',
    ('*', 'Base Metals'): '基础金属',
    ('Operator', 'Aluminium'): '铝',
    ('Operator', 'Copper'): '铜',
    ('Operator', 'Copper Fresnel'): '菲涅尔铜',
    ('Operator', 'Iron'): '铁',
    ('Operator', 'Lead'): '铅',
    ('Operator', 'Lead Rough'): '粗糙铅',
    ('Operator', 'Nickel'): '镍',
    ('Operator', 'Tin'): '锡',
    ('Operator', 'Titanium Polished'): '抛光钛',
    ('Operator', 'Titanium Textured'): '纹理钛',
    ('Operator', 'Zinc'): '锌',
    ('*', 'Alloys'): '合金',
    ('Operator', 'Brass'): '黄铜',
    ('Operator', 'Bronze'): '青铜',
    ('Operator', 'Chrome'): '铬',
    ('Operator', 'Steel'): '钢',
    ('*', 'Extras'): '额外的',
    ('Operator', 'Asphalt'): '沥青',
    ('Operator', 'Asphalt Bleached'): '白沥青',
    ('Operator', 'Glass Hack'): '玻璃投影',
    ('Operator', 'Mercury'): '水银',
    ('Operator', 'Red Metal'): '红金属',
    ('Operator', 'Rubber Cutting Mat'): '橡胶切割垫',
    ('Operator', 'Tinted Plaster'): '着色的石膏',
    ('Operator', 'Wall Paint'): '墙面漆',
  }
}
